Repository woowacourse-teams/2023-pium, pull requests merged in 2023-09, with the labels that each got.

#314 refactor: Theme 타입 적용 및 리팩터링
  frontend/public/assets/manifest.json
  frontend/src/apis/dictionary.ts
  frontend/src/apis/dictionaryPlant.ts
  frontend/src/apis/history.ts
  frontend/src/apis/petPlant.ts
  frontend/src/apis/reminder.ts
  frontend/src/components/dictionaryPlant/DictionaryPlantContent/index.tsx
  frontend/src/components/petPlant/PetPlantDetail/index.tsx
  frontend/src/components/petPlant/PetPlantEditForm/index.tsx
  frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
  frontend/src/components/petPlant/Timeline/index.tsx
  frontend/src/components/search/SearchBox/index.tsx
  frontend/src/components/search/SearchResults/index.tsx
  frontend/src/hooks/queries/dictionary/useDictSearch.ts
  frontend/src/hooks/queries/dictionaryPlant/useDictionaryPlantDetail.ts
  frontend/src/hooks/queries/dictionaryPlant/useDictionaryPlantSearch.ts
  frontend/src/hooks/queries/history/useYearList.ts
  frontend/src/hooks/queries/petPlant/useDeletePetPlant.ts
  frontend/src/hooks/queries/petPlant/useEditPetPlant.ts
  frontend/src/hooks/queries/petPlant/usePetPlantCardList.ts
  frontend/src/hooks/queries/petPlant/usePetPlantDetails.ts
  frontend/src/hooks/queries/petPlant/useRegisterPetPlant.ts
  frontend/src/hooks/queries/reminder/useChangeDate.ts
  frontend/src/hooks/queries/reminder/useReminder.ts
  frontend/src/hooks/queries/reminder/useWater.ts
  frontend/src/hooks/useCalendar.ts
  frontend/src/hooks/useDictionaryNavigate.ts
  frontend/src/hooks/useIntersectionRef.ts
  frontend/src/hooks/useReminderHooks.ts
  frontend/src/mocks/storage/History.ts
  frontend/src/pages/DictionaryPlantDetail/DictionaryPlantDetail.stories.tsx
  frontend/src/pages/DictionaryPlantDetail/DictionaryPlantDetail.style.ts
  frontend/src/pages/DictionaryPlantDetail/index.tsx
  frontend/src/pages/DictionaryPlantSearch/DictionaryPlantSearch.style.ts
  frontend/src/pages/DictionaryPlantSearch/index.tsx
  frontend/src/pages/Main/Main.style.tsx
  frontend/src/pages/Main/index.tsx
  frontend/src/pages/PetPlantCardList/index.tsx
  frontend/src/pages/PetPlantDetails/index.tsx
  frontend/src/pages/PetPlantEdit/index.tsx
  frontend/src/pages/PetPlantRegister/Form/Form.style.ts
  frontend/src/pages/PetPlantRegister/Form/index.tsx
  frontend/src/pages/PetPlantRegister/Search/Search.style.ts
  frontend/src/pages/PetPlantRegister/Search/index.tsx
  frontend/src/router.tsx
  frontend/src/style/styled-components.d.ts
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
  frontend/src/types/dictionaryPlant.ts
  frontend/src/utils/createObserver.ts
  frontend/webpack.config.js
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#343 feat: 모두의정원, 식물 등록 요청 엔티티 추가
  backend/pium/src/main/java/com/official/pium/admin/Registration.java
  backend/pium/src/main/java/com/official/pium/domain/Garden.java
  backend/pium/src/main/resources/db/migration/V3__add_garden_regist.sql
  backend/pium/src/main/resources/sql/schema.sql
Labels: 🌈 기능, 🍉 백엔드

#332 refactor: 마이페이지 회원 탈퇴 버튼 위치를 수정한다.
  frontend/src/components/@common/ContentHeader/ContentHeader.stories.tsx
  frontend/src/components/@common/ContentHeader/ContentHeader.style.ts
  frontend/src/components/@common/ContentHeader/index.tsx
  frontend/src/components/@common/VerticalDivider/VerticalDivider.style.ts
  frontend/src/pages/MyPage/MyPage.style.ts
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/PetPlantCardList/PetPlantCardList.style.ts
  frontend/src/pages/PetPlantCardList/index.tsx
  frontend/src/pages/Reminder/Reminder.style.ts
  frontend/src/pages/Reminder/index.tsx
  frontend/src/style/Global.style.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#333 feat: 어드민 페이지 구현
  backend/pium/build.gradle
  backend/pium/src/docs/asciidoc/dictionaryPlant.adoc
  backend/pium/src/main/java/com/official/pium/config/WebMvcConfigure.java
  backend/pium/src/main/java/com/official/pium/controller/AdminArgumentResolver.java
  backend/pium/src/main/java/com/official/pium/controller/AdminPageController.java
  backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
  backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
  backend/pium/src/main/java/com/official/pium/domain/Admin.java
  backend/pium/src/main/java/com/official/pium/domain/AdminAuth.java
  backend/pium/src/main/java/com/official/pium/domain/DictionaryPlant.java
  backend/pium/src/main/java/com/official/pium/exception/AuthorizationException.java
  backend/pium/src/main/java/com/official/pium/mapper/AdminMapper.java
  backend/pium/src/main/java/com/official/pium/mapper/DictionaryPlantMapper.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
  backend/pium/src/main/java/com/official/pium/service/AdminService.java
  backend/pium/src/main/java/com/official/pium/service/DictionaryPlantService.java
  backend/pium/src/main/java/com/official/pium/service/dto/AdminLoginRequest.java
  backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantCreateRequest.java
  backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantUpdateRequest.java
  backend/pium/src/main/resources/application.properties
  backend/pium/src/main/resources/static/css/styles.css
  backend/pium/src/main/resources/templates/admin/common/layout.html
  backend/pium/src/main/resources/templates/admin/dict/create.html
  backend/pium/src/main/resources/templates/admin/dict/list.html
  backend/pium/src/main/resources/templates/admin/dict/plant.html
  backend/pium/src/main/resources/templates/admin/dict/requests.html
  backend/pium/src/main/resources/templates/admin/dict/update.html
  backend/pium/src/main/resources/templates/admin/fragments/logout.html
  backend/pium/src/main/resources/templates/admin/fragments/nav.html
  backend/pium/src/main/resources/templates/admin/index.html
  backend/pium/src/main/resources/templates/admin/login.html
  backend/pium/src/test/java/com/official/pium/UITest.java
  backend/pium/src/test/java/com/official/pium/controller/AdminPageControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/AuthControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/domain/AdminTest.java
  backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java
  backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
  backend/pium/src/test/resources/application.properties
Labels: 🌈 기능, 🍉 백엔드

#353 fix: 정적파일 경로 수정
  backend/pium/src/main/java/com/official/pium/controller/AdminPageController.java
  backend/pium/src/test/java/com/official/pium/controller/AdminPageControllerTest.java
Labels: 🐛 버그, 🍉 백엔드

#340 feat: 모두의 정원 게시글 아이템 구현
  frontend/.storybook/decorators.tsx
  frontend/.storybook/preview.tsx
  frontend/src/components/@common/SeeMoreContentBox/SeeMoreContentBox.stories.tsx
  frontend/src/components/@common/SeeMoreContentBox/SeeMoreContentBox.styles.ts
  frontend/src/components/@common/SeeMoreContentBox/hooks/useShowState.ts
  frontend/src/components/@common/SeeMoreContentBox/index.tsx
  frontend/src/components/dictionaryPlant/DictionaryPlantContent/index.tsx
  frontend/src/components/garden/GardenPostItem/GardenPostItem.stories.tsx
  frontend/src/components/garden/GardenPostItem/GardenPostItem.styles.ts
  frontend/src/components/garden/GardenPostItem/index.tsx
  frontend/src/types/garden.ts
Labels: 🌈 기능, 🍇 프론트엔드

#349 feat: 사전 식물 등록 신청 페이지
  frontend/.storybook/preview.tsx
  frontend/src/apis/dictionaryPlantRegistration.ts
  frontend/src/components/@common/FormInputBox/FormInputBox.style.ts
  frontend/src/components/@common/FormInputBox/index.tsx
  frontend/src/components/search/SearchBox/SearchBox.style.ts
  frontend/src/components/search/SearchBox/index.tsx
  frontend/src/components/search/SearchResults/SearchResults.style.ts
  frontend/src/components/search/SearchResults/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/dictionaryPlantRegistration/useDictionaryPlantRegister.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/dictionaryPlantRegistration.ts
  frontend/src/pages/NewDictionaryPlantRequest/Form/Form.stories.tsx
  frontend/src/pages/NewDictionaryPlantRequest/Form/Form.style.ts
  frontend/src/pages/NewDictionaryPlantRequest/Form/index.tsx
  frontend/src/pages/NewDictionaryPlantRequest/NewDictionaryPlantRequest.style.ts
  frontend/src/pages/NewDictionaryPlantRequest/index.tsx
  frontend/src/router.tsx
  frontend/src/types/dictionaryPlantRegistration.ts
  frontend/src/utils/image.ts
Labels: 🌈 기능, 🍇 프론트엔드

#351 feat: 반려 식물 사진 업로드
  backend/pium/build.gradle
  backend/pium/src/main/java/com/official/pium/config/S3Config.java
  backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/PhotoManger.java
  backend/pium/src/main/java/com/official/pium/util/PhotoNameGenerator.java
  backend/pium/src/main/java/com/official/pium/util/PhotoS3Manager.java
  backend/pium/src/test/java/com/official/pium/AcceptanceTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/ReminderApiTest.java
  backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/fixture/FileFixture.java
  backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/util/PhotoNameGeneratorTest.java
  backend/pium/src/test/java/com/official/pium/util/PhotoS3ManagerTest.java
  backend/pium/src/test/resources/application.properties
Labels: 🌈 기능, 🌎 인프라, 🍉 백엔드

#360 refactor: 사전 식물 등록 신청 FormData 컨벤션을 맞춘다.
  frontend/src/apis/dictionaryPlantRegistration.ts
  frontend/src/components/search/SearchBox/SearchBox.style.ts
  frontend/src/components/search/SearchBox/index.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/NewDictionaryPlantRequest/Form/index.tsx
  frontend/src/utils/image.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#363 feat : 사전 식물 등록 요청 기능
  backend/pium/src/main/java/com/official/pium/admin/controller/RegistrationController.java
  backend/pium/src/main/java/com/official/pium/admin/domain/Registration.java
  backend/pium/src/main/java/com/official/pium/admin/dto/RegistrationRequest.java
  backend/pium/src/main/java/com/official/pium/admin/dto/RegistrationResponse.java
  backend/pium/src/main/java/com/official/pium/admin/mapper/RegistrationMapper.java
  backend/pium/src/main/java/com/official/pium/admin/repository/RegistrationRepository.java
  backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
  backend/pium/src/main/resources/application.properties
  backend/pium/src/test/java/com/official/pium/admin/controller/RegistrationControllerTest.java
  backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
  backend/pium/src/test/resources/application.properties
Labels: 🌈 기능, 🍉 백엔드

#357 feat: 사진 등록 기능 추가
  frontend/cypress/e2e/petPlantEdit.cy.ts
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/cypress/fixtures/success_image.png
  frontend/src/apis/petPlant.ts
  frontend/src/components/@common/Image/index.tsx
  frontend/src/components/@common/ImageButton/ImageButton.stories.tsx
  frontend/src/components/@common/ImageButton/ImageButton.style.ts
  frontend/src/components/@common/ImageButton/index.tsx
  frontend/src/components/@common/SvgIcons/SvgFill/index.tsx
  frontend/src/components/@common/SvgIcons/SvgSpriteMap.tsx
  frontend/src/components/petPlant/PetPlantEditForm/PetPlantEditForm.style.ts
  frontend/src/components/petPlant/PetPlantEditForm/index.tsx
  frontend/src/components/petPlant/PetPlantRegisterForm/PetPlantRegisterForm.style.ts
  frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
  frontend/src/hooks/image/useFileUpload.ts
  frontend/src/hooks/queries/petPlant/useEditPetPlant.ts
  frontend/src/hooks/queries/petPlant/useRegisterPetPlant.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/PetPlantRegister/Form/Form.style.ts
  frontend/src/pages/PetPlantRegister/Form/index.tsx
  frontend/src/types/image.ts
  frontend/src/utils/optimizeImage.ts
Labels: 🌈 기능, 🍇 프론트엔드

#370 fix: formData 타입 적용 후 수정
  frontend/src/apis/dictionaryPlantRegistration.ts
  frontend/src/apis/petPlant.ts
Labels: 🐛 버그, 🛠️ 리팩터링, 🍇 프론트엔드

#365 feat: 모두의 정원 구현
  backend/pium/src/docs/asciidoc/dictionaryPlant.adoc
  backend/pium/src/docs/asciidoc/garden.adoc
  backend/pium/src/docs/asciidoc/index.adoc
  backend/pium/src/docs/asciidoc/petPlant.adoc
  backend/pium/src/main/java/com/official/pium/admin/controller/RegistrationController.java
  backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
  backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
  backend/pium/src/main/java/com/official/pium/controller/GardenController.java
  backend/pium/src/main/java/com/official/pium/domain/Garden.java
  backend/pium/src/main/java/com/official/pium/mapper/GardenMapper.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/repository/GardenCustomRepository.java
  backend/pium/src/main/java/com/official/pium/repository/GardenCustomRepositoryImpl.java
  backend/pium/src/main/java/com/official/pium/repository/GardenRepository.java
  backend/pium/src/main/java/com/official/pium/service/GardenService.java
  backend/pium/src/main/java/com/official/pium/service/dto/GardenCreateRequest.java
  backend/pium/src/main/java/com/official/pium/service/dto/GardenResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/SingleGardenResponse.java
  backend/pium/src/main/resources/db/migration/V4_modify_garden_colum_type.sql
  backend/pium/src/main/resources/sql/schema.sql
  backend/pium/src/test/java/com/official/pium/AcceptanceTest.java
  backend/pium/src/test/java/com/official/pium/IntegrationTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/GardenApiTest.java
  backend/pium/src/test/java/com/official/pium/admin/controller/RegistrationControllerTest.java
  backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
  backend/pium/src/test/java/com/official/pium/controller/GardenControllerTest.java
  backend/pium/src/test/java/com/official/pium/fixture/GardenFixture.java
  backend/pium/src/test/java/com/official/pium/repository/GardenRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/GardenServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/GardenSupport.java
  backend/pium/src/test/java/com/official/pium/support/MemberSupport.java
Labels: 🌈 기능, 🍉 백엔드

#367 feat: (어드민) 사전 식물 등록 요청 확인
  backend/pium/src/main/java/com/official/pium/admin/controller/AdminArgumentResolver.java
  backend/pium/src/main/java/com/official/pium/admin/controller/AdminPageController.java
  backend/pium/src/main/java/com/official/pium/admin/mapper/AdminMapper.java
  backend/pium/src/main/java/com/official/pium/admin/service/AdminService.java
  backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
  backend/pium/src/main/java/com/official/pium/config/WebMvcConfigure.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/PhotoManager.java
  backend/pium/src/main/java/com/official/pium/util/PhotoS3Manager.java
  backend/pium/src/main/resources/application.properties
  backend/pium/src/main/resources/sql/schema.sql
  backend/pium/src/main/resources/templates/admin/dict/list.html
  backend/pium/src/main/resources/templates/admin/dict/requests.html
  backend/pium/src/test/java/com/official/pium/controller/AdminPageControllerTest.java
Labels: 🌈 기능, 🍉 백엔드

#372 hotfix: s3 업로드 불가 해결
  backend/pium/src/main/java/com/official/pium/util/PhotoS3Manager.java
  backend/pium/src/main/resources/db/migration/V4__modify_garden_colum_type.sql
  backend/pium/src/test/resources/application.properties
Labels: 🐛 버그, 🍉 백엔드

#377 refactor: 쿼리 개선
  .gitmodules
  backend/pium/src/main/java/com/official/pium/domain/HistoryCategory.java
  backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
  backend/pium/src/main/java/com/official/pium/event/history/HistoryEvents.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepository.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepositoryImpl.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
  backend/pium/src/main/java/com/official/pium/repository/MemberRepository.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
  backend/pium/src/main/java/com/official/pium/service/MemberService.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/util/PhotoS3Manager.java
  backend/pium/src/main/resources/db/migration/V5__modify_history_category.sql
  backend/pium/src/main/resources/sql/schema.sql
  backend/pium/src/test/java/com/official/pium/service/MemberServiceTest.java
  backend/pium/src/test/resources/application.properties
Labels: 🌎 인프라, 🍉 백엔드

#379 fix: 사전식물 등록 요청 사진 변경
  backend/pium/src/main/resources/templates/admin/dict/requests.html
Labels: 🐛 버그, 🍉 백엔드

#361 feat: 모두의 정원 페이지
  frontend/cypress/e2e/auth.cy.ts
  frontend/src/apis/garden.ts
  frontend/src/components/@common/SeeMoreContentBox/SeeMoreContentBox.styles.ts
  frontend/src/components/@common/SvgIcons/SvgFill/index.tsx
  frontend/src/components/@common/SvgIcons/SvgSpriteMap.tsx
  frontend/src/components/@common/SvgIcons/SvgStroke/index.tsx
  frontend/src/components/@common/Toast/ToastList.tsx
  frontend/src/components/dictionaryPlant/DictionaryPlantContent/DictionaryPlantContent.style.ts
  frontend/src/components/dictionaryPlant/DictionaryPlantContent/index.tsx
  frontend/src/components/petPlant/Timeline/TimelineSkeleton.tsx
  frontend/src/components/petPlant/Timeline/converter.ts
  frontend/src/components/petPlant/Timeline/index.tsx
  frontend/src/components/search/SearchBox/SearchBox.style.ts
  frontend/src/components/search/SearchBox/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/dictionaryPlant/useDictionaryPlantSearch.ts
  frontend/src/hooks/queries/garden/useGardenPostList.ts
  frontend/src/hooks/queries/history/useYearList.ts
  frontend/src/hooks/queries/petPlant/usePetPlantCardList.ts
  frontend/src/hooks/queries/reminder/useChangeDate.ts
  frontend/src/hooks/queries/reminder/useReminder.ts
  frontend/src/hooks/queries/reminder/useWater.ts
  frontend/src/hooks/useDictionaryPlantNavigate.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/garden.ts
  frontend/src/mocks/handlers/garden.ts
  frontend/src/mocks/handlers/gardenHandlers.ts
  frontend/src/mocks/storage/Reminder.ts
  frontend/src/pages/DictionaryPlantDetail/DictionaryPlantDetail.style.ts
  frontend/src/pages/DictionaryPlantDetail/index.tsx
  frontend/src/pages/DictionaryPlantSearch/index.tsx
  frontend/src/pages/GardenPostList/GardenPostItem/GardenPostItem.stories.tsx
  frontend/src/pages/GardenPostList/GardenPostItem/GardenPostItem.styles.ts
  frontend/src/pages/GardenPostList/GardenPostItem/GardenPostItemSkeleton.tsx
  frontend/src/pages/GardenPostList/GardenPostItem/index.tsx
  frontend/src/pages/GardenPostList/GardenPostList.style.ts
  frontend/src/pages/GardenPostList/GardenPostListHeader/GardenPostListHeader.style.ts
  frontend/src/pages/GardenPostList/GardenPostListHeader/index.tsx
  frontend/src/pages/GardenPostList/index.tsx
  frontend/src/pages/Main/index.tsx
  frontend/src/pages/PetPlantCardList/PetPlantCardList.style.ts
  frontend/src/pages/PetPlantRegister/Form/Form.style.ts
  frontend/src/pages/PetPlantRegister/Search/index.tsx
  frontend/src/router.tsx
  frontend/src/store/atoms/garden.ts
  frontend/src/style/theme.style.ts
  frontend/src/types/api.ts
  frontend/src/types/history.ts
Labels: 🌈 기능, 🍇 프론트엔드

#375 refactor: 최적화 리팩터링
  README.md
  frontend/.storybook/SvgIcon.tsx
  frontend/cypress/e2e/reminder.cy.ts
  frontend/generateSiteMap.js
  frontend/package.json
  frontend/public/fonts/NanumSquareRoundMissingGlyph.woff2
  frontend/public/fonts/font.css
  frontend/public/index.html
  frontend/public/seo/robots.txt
  frontend/public/seo/sitemap.xml
  frontend/src/components/@common/Calendar/Calendar.stories.tsx
  frontend/src/components/@common/Calendar/Calendar.style.ts
  frontend/src/components/@common/ContentHeader/ContentHeader.style.ts
  frontend/src/components/@common/FormInputBox/FormInputBox.style.ts
  frontend/src/components/@common/Image/index.tsx
  frontend/src/components/@common/Modal/Modal.style.ts
  frontend/src/components/@common/SvgIcons/SvgFill/index.tsx
  frontend/src/components/@common/SvgIcons/SvgSpriteMap.tsx
  frontend/src/components/dictionaryPlant/DictionaryPlantContent/DictionaryPlantContent.style.ts
  frontend/src/components/petPlant/PetPlantRegisterForm/PetPlantRegisterForm.style.ts
  frontend/src/components/reminder/Card/Card.style.ts
  frontend/src/components/reminder/Card/index.tsx
  frontend/src/components/reminder/CardBox/CardBox.style.ts
  frontend/src/components/reminder/MonthBox/MonthBox.style.ts
  frontend/src/components/reminder/MonthBox/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Error/Error.style.ts
  frontend/src/pages/Error/NotFound.tsx
  frontend/src/pages/Error/Unauthorize.tsx
  frontend/src/pages/Loading/index.tsx
  frontend/src/pages/Login/Login.style.ts
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/Main/Main.style.tsx
  frontend/src/pages/Main/index.tsx
  frontend/src/pages/MyPage/MyPage.style.ts
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/Reminder/Reminder.style.ts
  frontend/src/pages/Reminder/index.tsx
  frontend/src/style/Global.style.ts
  frontend/src/style/theme.style.ts
  frontend/webpack.config.js
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#387 refactor: 사전 식물 이미지 해상도를 조정한다
  .github/workflows/frontend-e2e-test.yml
  frontend/cypress/e2e/auth.cy.ts
  frontend/src/components/@common/Image/Image.style.ts
  frontend/src/components/@common/Image/index.tsx
  frontend/src/components/petPlant/PetPlantCard/index.tsx
  frontend/src/components/search/SearchBox/index.tsx
  frontend/src/utils/image.ts
Labels: 🍇 프론트엔드

#390 fix: 사용자 사진 업로드 시 미리보기가 안 바뀌는 문제
  frontend/src/components/@common/Image/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/image/useFileUpload.ts
  frontend/src/mocks/data/dictionaryPlant.ts
  frontend/src/mocks/data/garden.ts
  frontend/src/mocks/data/petPlantCardList.ts
  frontend/src/mocks/data/petPlants.ts
  frontend/src/mocks/data/reminder.ts
  frontend/src/mocks/data/search.ts
  frontend/src/utils/image.ts
Labels: 🐛 버그, 🍇 프론트엔드

#392 피움 1.1.1 버전 출시
  .github/workflows/frontend-e2e-test.yml
  frontend/cypress/e2e/auth.cy.ts
  frontend/package.json
  frontend/src/components/@common/CheckButton/CheckButton.style.ts
  frontend/src/components/@common/Confirm/Confirm.style.ts
  frontend/src/components/@common/Image/Image.style.ts
  frontend/src/components/@common/Image/index.tsx
  frontend/src/components/@common/InlineRadio/ingredients/Main.style.ts
  frontend/src/components/@common/Modal/index.tsx
  frontend/src/components/@common/Navbar/Navbar.style.ts
  frontend/src/components/@common/Select/Select.style.ts
  frontend/src/components/@common/Select/index.tsx
  frontend/src/components/@common/Toast/Toast.style.ts
  frontend/src/components/petPlant/PetPlantCard/PetPlantCard.style.ts
  frontend/src/components/petPlant/PetPlantCard/index.tsx
  frontend/src/components/petPlant/PetPlantDetail/PetPlantDetail.style.ts
  frontend/src/components/petPlant/PetPlantEditForm/PetPlantEditForm.style.ts
  frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
  frontend/src/components/petPlant/TimelineItemList/TimelineItemList.style.ts
  frontend/src/components/petPlant/TimelineItemList/index.tsx
  frontend/src/components/search/SearchBox/SearchBox.style.ts
  frontend/src/components/search/SearchBox/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/image/useFileUpload.ts
  frontend/src/mocks/data/dictionaryPlant.ts
  frontend/src/mocks/data/garden.ts
  frontend/src/mocks/data/petPlantCardList.ts
  frontend/src/mocks/data/petPlants.ts
  frontend/src/mocks/data/reminder.ts
  frontend/src/mocks/data/search.ts
  frontend/src/pages/DictionaryPlantDetail/DictionaryPlantDetail.style.ts
  frontend/src/pages/GardenPostList/GardenPostList.style.ts
  frontend/src/pages/GardenPostList/GardenPostListHeader/GardenPostListHeader.style.ts
  frontend/src/pages/GardenRegister/Form/FormSection/FormSection.style.ts
  frontend/src/pages/GardenRegister/Form/Profile/Profile.style.ts
  frontend/src/pages/GardenRegister/Pick/PetPlantPicker.style.ts
  frontend/src/pages/Main/Main.style.tsx
  frontend/src/pages/NewDictionaryPlantRequest/Form/Form.style.ts
  frontend/src/pages/PetPlantCardList/PetPlantCardList.style.ts
  frontend/src/pages/PetPlantRegister/Form/Form.style.ts
  frontend/src/pages/PetPlantRegister/Search/Search.style.ts
  frontend/src/style/Global.style.ts
  frontend/src/utils/image.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드, 🍉 백엔드

#407 fix: 반려 식물 수정 시 기존 이미지 제거
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/PhotoManager.java
  backend/pium/src/main/java/com/official/pium/util/PhotoS3Manager.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/util/PhotoS3ManagerTest.java
Labels: 🐛 버그, 🍉 백엔드
