Repository woowacourse-teams/2023-pium, pull requests merged in 2023-10, with the labels that each got.

#421 feat: 한 번 불러오기 실패한 사진은 다시 요청하지 않기
  frontend/src/components/@common/Image/index.tsx
  frontend/src/mocks/data/reminder.ts
  frontend/src/models/ImageSourceList.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#429 feat: 웹 푸시 구현
  .github/workflows/frontend-dev.yml
  frontend/cypress/e2e/main.cy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/android-icon-144x144.png
  frontend/public/assets/android-icon-192x192.png
  frontend/public/assets/android-icon-48x48.png
  frontend/public/assets/android-icon-512x512.png
  frontend/public/assets/android-icon-72x72.png
  frontend/public/assets/android-icon-96x96.png
  frontend/public/assets/apple-icon-114x114.png
  frontend/public/assets/apple-icon-120x120.png
  frontend/public/assets/apple-icon-144x144.png
  frontend/public/assets/apple-icon-152x152.png
  frontend/public/assets/apple-icon-180x180.png
  frontend/public/assets/apple-icon-192x192.png
  frontend/public/assets/apple-icon-512x512.png
  frontend/public/assets/apple-icon-57x57.png
  frontend/public/assets/apple-icon-60x60.png
  frontend/public/assets/apple-icon-72x72.png
  frontend/public/assets/apple-icon-76x76.png
  frontend/public/assets/apple-icon-precomposed.png
  frontend/public/assets/apple-icon.png
  frontend/public/assets/favicon-16x16.png
  frontend/public/assets/favicon-32x32.png
  frontend/public/assets/favicon-96x96.png
  frontend/public/assets/favicon.ico
  frontend/public/assets/manifest.json
  frontend/public/assets/ms-icon-144x144.png
  frontend/public/assets/ms-icon-150x150.png
  frontend/public/assets/ms-icon-310x310.png
  frontend/public/assets/ms-icon-70x70.png
  frontend/public/devLocalServiceWorker.js
  frontend/public/firebase-messaging-sw.js
  frontend/public/seo/sitemap.xml
  frontend/public/serviceWorker.js
  frontend/src/apis/webPush.ts
  frontend/src/components/@common/InstallPrompt/InstallPrompt.style.ts
  frontend/src/components/@common/InstallPrompt/index.tsx
  frontend/src/components/@common/Toggle/Toggle.stories.tsx
  frontend/src/components/@common/Toggle/Toggle.style.ts
  frontend/src/components/@common/Toggle/index.tsx
  frontend/src/hooks/@common/useInstallApp.ts
  frontend/src/hooks/@common/usePushAlert.ts
  frontend/src/hooks/queries/auth/useLogin.ts
  frontend/src/hooks/queries/auth/useWebPush.ts
  frontend/src/hooks/queries/petPlant/useRegisterPetPlant.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/@common/Main/index.tsx
  frontend/src/pages/auth/Login/Authorization.tsx
  frontend/src/pages/auth/MyPage/MyPage.style.ts
  frontend/src/pages/auth/MyPage/index.tsx
  frontend/src/registerServiceWork.ts
  frontend/src/swDev.ts
  frontend/src/utils/firebase.ts
  frontend/src/utils/pushStatus.ts
  frontend/src/utils/throwOnInvalidStatus.ts
  frontend/webpack.config.js
Labels: 🌈 기능, 🍇 프론트엔드

#427 feat: 전역 suspense 개선
  frontend/src/App.tsx
  frontend/src/components/@common/Calendar/index.tsx
  frontend/src/components/@common/PageLoadingBar/PageLoadingBar.style.ts
  frontend/src/components/@common/PageLoadingBar/index.tsx
  frontend/src/components/@common/PageLogger/index.tsx
  frontend/src/components/@common/SeeMoreContentBox/index.tsx
  frontend/src/hooks/@common/useCalendar.ts
  frontend/src/hooks/@common/useShowState.ts
  frontend/src/mocks/browser.ts
  frontend/src/pages/@common/Home/Home.style.tsx
  frontend/src/pages/@common/Home/index.tsx
  frontend/src/pages/@common/LastPageLoading/index.tsx
  frontend/src/pages/@common/RootTemplate/index.tsx
  frontend/src/pages/auth/MyPage/MyPage.style.ts
  frontend/src/pages/auth/MyPage/index.tsx
  frontend/src/pages/dictionaryPlant/DictionaryPlantDetail/index.tsx
  frontend/src/pages/dictionaryPlant/DictionaryPlantSearch/index.tsx
  frontend/src/pages/dictionaryPlant/NewDictionaryPlantRequest/index.tsx
  frontend/src/pages/garden/GardenPostList/index.tsx
  frontend/src/pages/garden/GardenRegisterForm/index.tsx
  frontend/src/pages/garden/GardenRegisterPick/index.tsx
  frontend/src/pages/petPlant/PetPlantCardList/index.tsx
  frontend/src/pages/petPlant/PetPlantDetails/index.tsx
  frontend/src/pages/petPlant/PetPlantEdit/index.tsx
  frontend/src/pages/petPlant/PetPlantRegister/Form/index.tsx
  frontend/src/pages/petPlant/PetPlantRegister/Search/Search.style.ts
  frontend/src/pages/petPlant/PetPlantRegister/Search/index.tsx
  frontend/src/pages/petPlant/PetPlantTimeline/index.tsx
  frontend/src/pages/reminder/ReminderPage/ReminderPage.style.ts
  frontend/src/pages/reminder/ReminderPage/index.tsx
  frontend/src/router.tsx
  frontend/src/store/atoms/@common.ts
Labels: 🌈 기능, 🛠️ 리팩터링, 🍇 프론트엔드

#432 Fix: 로그인 되지 않던 이슈 해결
  frontend/src/hooks/queries/auth/useLogin.ts
  frontend/src/pages/auth/Login/Authorization.tsx
Labels: 🐛 버그, 🍇 프론트엔드

#430 feat: 푸시 알림 기능
  backend/pium/build.gradle
  backend/pium/src/docs/asciidoc/index.adoc
  backend/pium/src/docs/asciidoc/member.adoc
  backend/pium/src/main/java/com/official/pium/admin/controller/AdminPageController.java
  backend/pium/src/main/java/com/official/pium/admin/dto/AdminSendNotificationRequest.java
  backend/pium/src/main/java/com/official/pium/config/ScheduleConfig.java
  backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
  backend/pium/src/main/java/com/official/pium/controller/MemberController.java
  backend/pium/src/main/java/com/official/pium/domain/Member.java
  backend/pium/src/main/java/com/official/pium/event/notification/NotificationEvent.java
  backend/pium/src/main/java/com/official/pium/event/notification/NotificationEventListener.java
  backend/pium/src/main/java/com/official/pium/fcm/dto/FcmMessageResponse.java
  backend/pium/src/main/java/com/official/pium/fcm/exception/FcmException.java
  backend/pium/src/main/java/com/official/pium/fcm/service/FcmMessageSender.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantCustomRepository.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantCustomRepositoryImpl.java
  backend/pium/src/main/java/com/official/pium/service/MemberService.java
  backend/pium/src/main/java/com/official/pium/service/NotificationService.java
  backend/pium/src/main/java/com/official/pium/service/ReminderService.java
  backend/pium/src/main/java/com/official/pium/service/dto/NotificationCheckResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/NotificationSubscribeRequest.java
  backend/pium/src/main/java/com/official/pium/util/MessageSendManager.java
  backend/pium/src/main/resources/application.properties
  backend/pium/src/main/resources/db/migration/V6__modify_member_add_device_token.sql
  backend/pium/src/main/resources/sql/data.sql
  backend/pium/src/main/resources/sql/schema.sql
  backend/pium/src/main/resources/templates/admin/dict/create.html
  backend/pium/src/main/resources/templates/admin/dict/update.html
  backend/pium/src/main/resources/templates/admin/index.html
  backend/pium/src/main/resources/templates/admin/login.html
  backend/pium/src/main/resources/templates/admin/member/requests.html
  backend/pium/src/test/java/com/official/pium/UITest.java
  backend/pium/src/test/java/com/official/pium/acceptance/AuthApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/GardenApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/MemberApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/ReminderApiTest.java
  backend/pium/src/test/java/com/official/pium/controller/AdminPageControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/AuthControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/MemberControllerTest.java
  backend/pium/src/test/java/com/official/pium/fixture/NotificationFixture.java
  backend/pium/src/test/java/com/official/pium/service/GardenServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/MemberServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/MemberSupport.java
  backend/pium/src/test/resources/application.properties
Labels: 🌈 기능, 🍉 백엔드

#434 feat: 개인정보 처리 방침 추가
  frontend/src/components/@common/Footer/Footer.style.ts
  frontend/src/components/@common/Footer/index.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/@common/Privacy/Privacy.style.ts
  frontend/src/pages/@common/Privacy/index.tsx
  frontend/src/pages/auth/MyPage/index.tsx
  frontend/src/router.tsx
Labels: 📝 문서, 🌈 기능, 🍇 프론트엔드

#438 docs: 사용자 목록 페이지 수정
  backend/pium/src/main/resources/templates/admin/member/requests.html
Labels: 🐛 버그, 🍉 백엔드

#440 fix: 알림 등록 요청 변수명 변경 deviceToken -> token
  backend/pium/src/main/java/com/official/pium/service/MemberService.java
  backend/pium/src/main/java/com/official/pium/service/dto/NotificationSubscribeRequest.java
  backend/pium/src/test/java/com/official/pium/controller/MemberControllerTest.java
  backend/pium/src/test/java/com/official/pium/service/MemberServiceTest.java
Labels: 🐛 버그, 🍉 백엔드

#435 feat: 내비게이션 바 애니메이션 추가
  frontend/src/components/@common/Navbar/NavItem.style.ts
  frontend/src/components/@common/Navbar/NavItem.tsx
  frontend/src/components/@common/Navbar/Navbar.style.ts
  frontend/src/components/@common/Navbar/index.tsx
  frontend/src/components/@common/PageLoadingBar/index.tsx
  frontend/src/components/@common/Toast/index.tsx
  frontend/src/hooks/@common/useChildrenLeftPositions.ts
  frontend/src/hooks/@common/useIntersectionRef.ts
  frontend/src/hooks/@common/useNavbarRoofAnimation.ts
  frontend/src/pages/@common/Home/index.tsx
  frontend/src/pages/@common/RootTemplate/index.tsx
  frontend/src/pages/auth/MyPage/index.tsx
  frontend/src/pages/dictionaryPlant/DictionaryPlantSearch/index.tsx
  frontend/src/pages/dictionaryPlant/NewDictionaryPlantRequest/index.tsx
  frontend/src/pages/garden/GardenPostList/index.tsx
  frontend/src/pages/garden/GardenRegisterForm/index.tsx
  frontend/src/pages/garden/GardenRegisterPick/index.tsx
  frontend/src/pages/petPlant/PetPlantCardList/index.tsx
  frontend/src/pages/petPlant/PetPlantDetails/index.tsx
  frontend/src/pages/petPlant/PetPlantRegister/Search/index.tsx
  frontend/src/pages/petPlant/PetPlantTimeline/index.tsx
  frontend/src/pages/reminder/ReminderPage/index.tsx
Labels: 🌈 기능, 🛠️ 리팩터링, 🍇 프론트엔드

#442 feat: 세션 동기화 구현
  backend/pium/build.gradle
  backend/pium/src/main/java/com/official/pium/config/TimeConfig.java
  backend/pium/src/main/java/com/official/pium/config/WebMvcConfigure.java
  backend/pium/src/main/java/com/official/pium/controller/AuthController.java
  backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
  backend/pium/src/main/java/com/official/pium/controller/MemberArgumentResolver.java
  backend/pium/src/main/java/com/official/pium/domain/SessionGroup.java
  backend/pium/src/main/java/com/official/pium/exception/AuthenticationException.java
  backend/pium/src/main/java/com/official/pium/repository/SessionGroupRepository.java
  backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
  backend/pium/src/main/resources/application.properties
  backend/pium/src/main/resources/db/migration/V7__session_group.sql
  backend/pium/src/main/resources/sql/schema.sql
  backend/pium/src/test/java/com/official/pium/IntegrationTest.java
  backend/pium/src/test/java/com/official/pium/UITest.java
  backend/pium/src/test/java/com/official/pium/domain/SessionGroupTest.java
  backend/pium/src/test/java/com/official/pium/fixture/SessionGroupFixture.java
  backend/pium/src/test/java/com/official/pium/repository/SessionGroupRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/SessionGroupServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/SessionGroupSupport.java
Labels: 🛠️ 리팩터링, 🍉 백엔드

#445 refactor: 토글 안되는거 해결
  frontend/cypress/e2e/main.cy.ts
  frontend/cypress/e2e/navbar.cy.ts
  frontend/cypress/e2e/petPlantEdit.cy.ts
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/cypress/e2e/reminder.cy.ts
  frontend/public/firebase-messaging-sw.js
  frontend/src/components/mypage/PushAlert/PushAlert.style.ts
  frontend/src/components/mypage/PushAlert/index.tsx
  frontend/src/hooks/@common/useInstallApp.ts
  frontend/src/hooks/@common/usePushAlert.ts
  frontend/src/hooks/queries/auth/useWebPush.ts
  frontend/src/mocks/handlers.ts
  frontend/src/models/PushStatus.ts
  frontend/src/pages/auth/MyPage/MyPage.style.ts
  frontend/src/pages/auth/MyPage/index.tsx
  frontend/src/registerServiceWork.ts
  frontend/src/utils/firebase.ts
  frontend/src/utils/pushStatus.ts
  frontend/src/utils/throwOnInvalidStatus.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#450 fix: 내비게이션 바 버그 수정
  frontend/src/components/@common/Navbar/Navbar.style.ts
  frontend/src/components/@common/Navbar/index.tsx
  frontend/src/hooks/queries/auth/useLogin.ts
  frontend/src/hooks/queries/auth/useWithdraw.ts
  frontend/src/pages/@common/RootTemplate/index.tsx
Labels: 🐛 버그, 🍇 프론트엔드

#453 fix: 요청 발생 시 HttpSession 제거하도록 변경
  backend/pium/src/main/java/com/official/pium/controller/AuthController.java
  backend/pium/src/main/java/com/official/pium/controller/MemberArgumentResolver.java
  backend/pium/src/test/java/com/official/pium/UITest.java
  backend/pium/src/test/java/com/official/pium/acceptance/GardenApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/ReminderApiTest.java
  backend/pium/src/test/java/com/official/pium/controller/AuthControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/GardenControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/MemberControllerTest.java
Labels: 🐛 버그, 🍉 백엔드

#448 feat: 레이아웃 변경
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/src/components/@common/BackHeader/BackHeader.style.ts
  frontend/src/components/@common/BackHeader/index.tsx
  frontend/src/components/@common/CheckButton/CheckButton.style.ts
  frontend/src/components/petPlant/PetPlantDetail/PetPlantDetail.style.ts
  frontend/src/components/petPlant/PetPlantDetail/index.tsx
  frontend/src/pages/dictionaryPlant/DictionaryPlantDetail/DictionaryPlantDetail.style.ts
  frontend/src/pages/dictionaryPlant/DictionaryPlantDetail/index.tsx
  frontend/src/pages/petPlant/PetPlantDetails/index.tsx
  frontend/src/pages/petPlant/PetPlantRegister/Form/Form.style.ts
  frontend/src/pages/petPlant/PetPlantRegister/Form/index.tsx
  frontend/src/pages/petPlant/PetPlantRegister/Search/index.tsx
  frontend/src/pages/petPlant/PetPlantTimeline/PetPlantTimeline.style.ts
  frontend/src/pages/petPlant/PetPlantTimeline/index.tsx
Labels: 🍇 프론트엔드

#455 fix: 메모리 세션 구문 제거
  backend/pium/src/main/java/com/official/pium/controller/AuthController.java
  backend/pium/src/main/java/com/official/pium/controller/MemberController.java
  backend/pium/src/main/java/com/official/pium/exception/AuthorizationException.java
  backend/pium/src/main/java/com/official/pium/repository/SessionGroupRepository.java
  backend/pium/src/main/java/com/official/pium/service/MemberService.java
  backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
  backend/pium/src/test/java/com/official/pium/controller/MemberControllerTest.java
Labels: 🐛 버그, 🍉 백엔드

#457 fix: 어드민 post 수정
  backend/pium/src/main/resources/templates/admin/member/requests.html
Labels: 🐛 버그, 🍉 백엔드

#459 fix: 어드민 post 수정
  backend/pium/src/main/resources/sql/data.sql
  backend/pium/src/main/resources/templates/admin/member/requests.html
Labels: 🐛 버그, 🍉 백엔드

#461 fix: 로그인 시 세션이 존재할 경우 정상 반환
  backend/pium/src/main/java/com/official/pium/repository/SessionGroupRepository.java
  backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
  backend/pium/src/test/java/com/official/pium/repository/SessionGroupRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/SessionGroupServiceTest.java
Labels: 🐛 버그, 🍉 백엔드

#463 fix: 쿠키 요청 구분 보완
  backend/pium/src/main/java/com/official/pium/controller/HttpCookieManager.java
  backend/pium/src/main/java/com/official/pium/controller/MemberArgumentResolver.java
  backend/pium/src/test/java/com/official/pium/controller/HttpCookieManagerTest.java
Labels: 🐛 버그, 🍉 백엔드

#465 fix: 세션 조회 로직 변경
  backend/pium/src/main/java/com/official/pium/repository/SessionGroupRepository.java
  backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
  backend/pium/src/main/resources/db/migration/V8__session_group_drop_unique.sql
  backend/pium/src/test/java/com/official/pium/repository/SessionGroupRepositoryTest.java
Labels: 🐛 버그, 🍉 백엔드

#467 fix: 쿠키 조회 로직 변경
  backend/pium/src/main/java/com/official/pium/controller/HttpCookieManager.java
  backend/pium/src/main/resources/db/migration/V8__session_group_drop_unique.sql
  backend/pium/src/test/java/com/official/pium/controller/HttpCookieManagerTest.java
Labels: 🐛 버그, 🍉 백엔드

#469 FCM 에러 해결
  frontend/src/components/mypage/PushAlert/PushToggle.tsx
  frontend/src/components/mypage/PushAlert/index.tsx
  frontend/src/hooks/@common/usePushAlert.ts
  frontend/src/hooks/queries/auth/useWebPush.ts
  frontend/src/models/FCMMessaging.ts
  frontend/src/models/PushStatus.ts
  frontend/src/registerServiceWork.ts
  frontend/src/utils/firebase.ts
Labels: 🐛 버그, 🍇 프론트엔드
