Repository woowacourse-teams/2023-pium, pull requests merged in 2023-07, with the labels that each got.

#4 build: 프론트엔드 초기 설정
  frontend/.babelrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/index.html
  frontend/mockServiceWorker.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.stories.tsx
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 🌎 인프라, 🍇 프론트엔드

#3 build: 백엔드 초기 설정
  backend/pium/.gitignore
  backend/pium/build.gradle
  backend/pium/gradle/wrapper/gradle-wrapper.jar
  backend/pium/gradle/wrapper/gradle-wrapper.properties
  backend/pium/gradlew
  backend/pium/gradlew.bat
  backend/pium/settings.gradle
  backend/pium/src/main/java/com/official/pium/PiumApplication.java
  backend/pium/src/main/resources/application.properties
  backend/pium/src/test/java/com/official/pium/PiumApplicationTests.java
Labels: 🌎 인프라, 🍉 백엔드

#6 build: 프론트엔드 lint규칙 설정
  frontend/.eslintrc
  frontend/.stylelintrc
  frontend/package-lock.json
  frontend/package.json
Labels: 🌎 인프라, 🍇 프론트엔드

#8 fix: eslint ignorePatterns 추가
  frontend/.eslintrc
Labels: 🐛 버그, 🌎 인프라, 🍇 프론트엔드

#31 feature: 2차 데모데이에 필요한 msw 설정
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/dictionaryPlant.ts
  frontend/src/mocks/data/search.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storage/PetPlant.ts
  frontend/src/mocks/storybookHandlers.ts
  frontend/src/types/api/DataResponse.ts
  frontend/src/types/api/dictionary.ts
  frontend/src/types/api/petPlant.ts
  frontend/webpack.config.js
Labels: 🌈 기능, 🍇 프론트엔드

#32 feat: 데이터베이스 스키마 구성
  backend/pium/.gitignore
  backend/pium/src/main/java/com/official/pium/PiumApplication.java
  backend/pium/src/main/java/com/official/pium/domain/BaseEntity.java
  backend/pium/src/main/java/com/official/pium/domain/DictionaryPlant.java
  backend/pium/src/main/java/com/official/pium/domain/Member.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/domain/WaterCycle.java
  backend/pium/src/main/java/com/official/pium/repository/DictionaryPlantRepository.java
  backend/pium/src/main/java/com/official/pium/repository/MemberRepository.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
  backend/pium/src/main/resources/application.properties
  backend/pium/src/main/resources/sql/schema.sql
  backend/pium/src/test/java/com/official/pium/repository/DictionaryPlantRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
Labels: 🌈 기능, 🍉 백엔드

#36 build: tsconfig에 webpack alias 절대경로 추가
  frontend/tsconfig.json
Labels: 🌎 인프라, 🍇 프론트엔드

#38 fix: Repository 인터페이스 접근 제어자 추가
  backend/pium/src/main/java/com/official/pium/repository/DictionaryPlantRepository.java
  backend/pium/src/main/java/com/official/pium/repository/MemberRepository.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
Labels: 🐛 버그, 🍉 백엔드

#41 build: 백엔드 CI workflow 추가
  .github/workflows/backend-dev.yml
Labels: 🌎 인프라, 🍉 백엔드

#33 chore: husky 설정
  .husky/commit-msg
  frontend/package-lock.json
  frontend/package.json
Labels: 🌈 기능, 🍇 프론트엔드

#45 design: 전역 스타일링 설정
  frontend/.storybook/decolators.tsx
  frontend/.storybook/preview.ts
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/style/Global.style.ts
  frontend/src/style/GlobalFont.style.ts
  frontend/src/style/reset.style.ts
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
  frontend/webpack.config.js
Labels: 🌈 기능, 🌎 인프라, 🍇 프론트엔드

#49 fix: 스토리북에서 오타로 인한 버그 수정
  frontend/.storybook/decorators.tsx
  frontend/.storybook/main.ts
Labels: 🐛 버그, 🍇 프론트엔드

#51 Fix: tsconfig에 esModuleInterop: true로 설정
  frontend/tsconfig.json
Labels: 🐛 버그, 🍇 프론트엔드

#52 build: Gradle 빌드 결과물 버전 제거
  backend/pium/build.gradle
Labels: 🌎 인프라, 🍉 백엔드

#57 docs: README 팀 소개 작성
  README.md
Labels: 📝 문서

#58 Feature/21 달력 입력을 위한 컴포넌트 구현
  frontend/.storybook/decorators.tsx
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DateInput/DateInput.stories.tsx
  frontend/src/components/DateInput/DateInput.style.ts
  frontend/src/components/DateInput/index.tsx
  frontend/src/utils/date.ts
  frontend/tsconfig.json
Labels: 🌈 기능, 🍇 프론트엔드

#53 feature/44 메인 페이지 구현 및 msw 연결
  frontend/.prettierrc
  frontend/.storybook/main.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.stories.tsx
  frontend/src/App.tsx
  frontend/src/apis/search.ts
  frontend/src/assets/logo.svg
  frontend/src/components/SearchBox/SearchBox.style.ts
  frontend/src/components/SearchBox/index.tsx
  frontend/src/constants/index.ts
  frontend/src/index.tsx
  frontend/src/pages/Main/Main.style.tsx
  frontend/src/pages/Main/index.tsx
  frontend/src/pages/Root/Root.style.tsx
  frontend/src/pages/Root/index.tsx
  frontend/src/router.tsx
  frontend/src/style/Global.style.ts
  frontend/src/style/reset.style.ts
  frontend/src/types/module.d.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 🌈 기능, 🍇 프론트엔드

#62 chore: 스토리북 view port addon 적용
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/Root/Root.style.tsx
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
Labels: 🌈 기능, 🍇 프론트엔드

#42 feat: 반려 식물 등록 기능 구현
  backend/pium/build.gradle
  backend/pium/src/main/java/com/official/pium/PiumApplication.java
  backend/pium/src/main/java/com/official/pium/config/JpaAuditingConfig.java
  backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
  backend/pium/src/main/java/com/official/pium/domain/DictionaryPlant.java
  backend/pium/src/main/java/com/official/pium/domain/Member.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/domain/WaterCycle.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/dto/PetPlantRequest.java
  backend/pium/src/main/java/com/official/pium/service/dto/PetPlantResponse.java
  backend/pium/src/main/resources/application.properties
  backend/pium/src/test/java/com/official/pium/IntegrationTest.java
  backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/MemberFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/DictionaryPlantSupport.java
  backend/pium/src/test/java/com/official/pium/support/MemberSupport.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 🌈 기능, 🍉 백엔드

#60 feat: 라벨, 사전 정보, 선택형 사전 정보 컴포넌트 구현
  frontend/src/components/DictInfo/DictInfo.stories.tsx
  frontend/src/components/DictInfo/index.tsx
  frontend/src/components/DictInfo/ingredients/Main.style.ts
  frontend/src/components/DictInfo/ingredients/Main.tsx
  frontend/src/components/DictInfo/ingredients/Title.style.tsx
  frontend/src/components/DictInfoSwitch/DictInfoSwitch.stories.tsx
  frontend/src/components/DictInfoSwitch/index.tsx
  frontend/src/components/InlineRadio/InlineRadio.stories.tsx
  frontend/src/components/InlineRadio/index.tsx
  frontend/src/components/InlineRadio/ingredients/Main.style.ts
  frontend/src/components/InlineRadio/ingredients/Main.tsx
  frontend/src/components/InlineRadio/ingredients/Option.style.ts
  frontend/src/components/InlineRadio/ingredients/Option.tsx
  frontend/src/components/Tag/Tag.stories.tsx
  frontend/src/components/Tag/Tag.style.ts
  frontend/src/components/Tag/index.tsx
  frontend/src/constants/index.ts
  frontend/src/contexts/radioContext.tsx
  frontend/src/hooks/useRadioContext.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storybookHandlers.ts
  frontend/src/utils/getFilteredChildren.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 🌈 기능, 🍇 프론트엔드

#67 feat: 반려 식물 단일 조회
  backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
  backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/exception/dto/GlobalExceptionResponse.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
  backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
  backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 🌈 기능, 🍉 백엔드

#71 feat: 이미지 컴포넌트
  frontend/src/assets/sadpiumi.png
  frontend/src/components/Image/Image.stories.tsx
  frontend/src/components/Image/Image.style.ts
  frontend/src/components/Image/index.tsx
Labels: 🌈 기능, 🍇 프론트엔드

#69 feat: 사전 식물 검색기능 구현
  backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
  backend/pium/src/main/java/com/official/pium/mapper/DictionaryPlantMapper.java
  backend/pium/src/main/java/com/official/pium/repository/DictionaryPlantRepository.java
  backend/pium/src/main/java/com/official/pium/service/DictionaryPlantService.java
  backend/pium/src/main/java/com/official/pium/service/dto/DataResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantSearchResponse.java
  backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java
  backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
Labels: 🌈 기능, 🍉 백엔드

#78 feat: 셀렉터 구현
  frontend/src/components/Select/Select.stories.tsx
  frontend/src/components/Select/Select.style.ts
  frontend/src/components/Select/index.tsx
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
Labels: 🌈 기능, 🍇 프론트엔드

#72 feat: 사전 식물 상세 정보 조회 기능 구현
  backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
  backend/pium/src/main/java/com/official/pium/mapper/DictionaryPlantMapper.java
  backend/pium/src/main/java/com/official/pium/service/DictionaryPlantService.java
  backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantResponse.java
  backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java
  backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
Labels: 🌈 기능, 🍉 백엔드

#70 feat: 입력 폼 공통 컴포넌트 구현
  frontend/src/components/DateInput/DateInput.style.ts
  frontend/src/components/FormInputBox/FormInputBox.stories.tsx
  frontend/src/components/FormInputBox/FormInputBox.style.ts
  frontend/src/components/FormInputBox/index.tsx
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
  frontend/src/types/inputs.ts
Labels: 🌈 기능, 🍇 프론트엔드

#81 feat: 스택형 UI 구현
  frontend/package.json
  frontend/src/components/Stack/Stack.stories.tsx
  frontend/src/components/Stack/contexts/stackContext.tsx
  frontend/src/components/Stack/hooks/useStackContext.ts
  frontend/src/components/Stack/index.tsx
  frontend/src/components/Stack/ingredients/Element.tsx
  frontend/src/components/Stack/ingredients/Main.style.ts
  frontend/src/components/Stack/ingredients/Main.tsx
  frontend/src/constants/index.ts
Labels: 🌈 기능, 🍇 프론트엔드

#68 feat: 반려 식물 전체 조회
  backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
  backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
  backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/exception/dto/GlobalExceptionResponse.java
  backend/pium/src/main/java/com/official/pium/mapper/DictionaryPlantMapper.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
  backend/pium/src/main/java/com/official/pium/service/DictionaryPlantService.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/dto/DataResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantSearchResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/SinglePetPlantResponse.java
  backend/pium/src/test/java/com/official/pium/PiumApplicationTests.java
  backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
  backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/MemberFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
  backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 🌈 기능, 🍉 백엔드

#86 chore: react-query 설정
  frontend/.eslintrc
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
Labels: 🍇 프론트엔드

#80 feat: 반려 식물 등록 입력 컴포넌트 생성 (number 생성)
  frontend/src/components/DateInput/DateInput.stories.tsx
  frontend/src/components/DateInput/index.tsx
  frontend/src/components/FormInput/FormInput.stories.tsx
  frontend/src/components/FormInput/FormInput.style.ts
  frontend/src/components/FormInput/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useDateInput.ts
  frontend/src/hooks/useNumberInput.ts
  frontend/src/utils/validate.ts
Labels: 🌈 기능, 🍇 프론트엔드

#94 feat: 사전 식물 공공데이터 데이터 추가
  backend/pium/src/main/resources/application.properties
  backend/pium/src/main/resources/sql/data.sql
Labels: 🌈 기능, 🌎 인프라, 🍉 백엔드

#91 feat: 메인 페이지 검색 기능 고도화
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/dictionary.ts
  frontend/src/apis/search.ts
  frontend/src/components/SearchBox/SearchBox.style.ts
  frontend/src/components/SearchBox/index.tsx
  frontend/src/hooks/useDebounce.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storybookHandlers.ts
  frontend/src/pages/Main/Main.style.tsx
  frontend/src/queries/dictionaryPlants.ts
Labels: 🌈 기능, 🍇 프론트엔드

#90 feat: 식물 상세페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/dict.ts
  frontend/src/components/DictInfoSwitch/index.tsx
  frontend/src/components/InlineRadio/ingredients/Option.style.ts
  frontend/src/components/Tag/Tag.style.ts
  frontend/src/components/Tag/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useDictionaryPlants.ts
  frontend/src/hooks/useInvalidIdParams.ts
  frontend/src/index.tsx
  frontend/src/mocks/data/dictionaryPlant.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storybookHandlers.ts
  frontend/src/pages/DictionaryDetail/DictionaryDetail.stories.tsx
  frontend/src/pages/DictionaryDetail/DictionaryDetail.style.ts
  frontend/src/pages/DictionaryDetail/index.tsx
  frontend/src/pages/Root/Root.style.tsx
  frontend/src/router.tsx
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
  frontend/src/types/api/dictionary.ts
  frontend/src/types/plants.ts
  frontend/webpack.config.js
Labels: 🌈 기능, 🍇 프론트엔드

#96 feat: 반려 식물 등록 페이지 구현
  frontend/src/apis/dict.ts
  frontend/src/apis/dictionary.ts
  frontend/src/apis/pet.ts
  frontend/src/components/DateInput/DateInput.stories.tsx
  frontend/src/components/DateInput/DateInput.style.ts
  frontend/src/components/DateInput/index.tsx
  frontend/src/components/FormInput/FormInput.style.ts
  frontend/src/components/FormInput/index.tsx
  frontend/src/components/FormInputBox/FormInputBox.style.ts
  frontend/src/components/FormInputBox/index.tsx
  frontend/src/components/SearchBox/SearchBox.style.ts
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/Select/Select.style.ts
  frontend/src/components/Select/index.tsx
  frontend/src/components/Stack/Stack.stories.tsx
  frontend/src/components/Stack/contexts/stackContext.tsx
  frontend/src/components/Stack/hooks/useStack.ts
  frontend/src/components/Stack/hooks/useStackContext.ts
  frontend/src/components/Stack/ingredients/Element.tsx
  frontend/src/components/Stack/ingredients/Main.style.ts
  frontend/src/components/Stack/ingredients/Main.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useDictionaryPlants.ts
  frontend/src/hooks/useInvalidIdParams.ts
  frontend/src/pages/DictionaryDetail/DictionaryDetail.style.ts
  frontend/src/pages/Main/index.tsx
  frontend/src/pages/PetRegister/Form/Form.style.ts
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/pages/PetRegister/Form/reducer.ts
  frontend/src/pages/PetRegister/Search/Search.style.ts
  frontend/src/pages/PetRegister/Search/index.tsx
  frontend/src/router.tsx
Labels: 🌈 기능, 🍇 프론트엔드

#100 feat: 사전 식물 검색 결과 페이지
  frontend/src/components/DateInput/DateInput.style.ts
  frontend/src/components/DateInput/index.tsx
  frontend/src/components/FormInput/FormInput.stories.tsx
  frontend/src/components/FormInput/FormInput.style.ts
  frontend/src/components/FormInput/index.tsx
  frontend/src/components/InlineRadio/ingredients/Option.style.ts
  frontend/src/components/SearchBox/SearchBox.stories.tsx
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/SearchResultItem/SearchResultItem.stories.tsx
  frontend/src/components/SearchResultItem/SearchResultItem.style.ts
  frontend/src/components/SearchResultItem/index.tsx
  frontend/src/components/SearchResults/SearchResults.stories.tsx
  frontend/src/components/SearchResults/SearchResults.style.ts
  frontend/src/components/SearchResults/index.tsx
  frontend/src/components/Select/Select.style.ts
  frontend/src/components/Select/index.tsx
  frontend/src/hooks/useDictrionaryNavigate.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storybookHandlers.ts
  frontend/src/pages/DictionaryDetail/index.tsx
  frontend/src/pages/DictionarySearch/DictionarySearch.style.ts
  frontend/src/pages/DictionarySearch/index.tsx
  frontend/src/pages/Main/index.tsx
  frontend/src/pages/PetRegister/Form/Form.style.ts
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/pages/PetRegister/Search/index.tsx
  frontend/src/router.tsx
  frontend/src/utils/date.ts
  frontend/src/utils/getFilteredChildren.ts
  frontend/src/utils/parseTemperature.ts
  frontend/src/utils/validate.ts
Labels: 🌈 기능, 🍇 프론트엔드

#104 refactor: react icons 제거 후 개별 svg 아이콘으로 교체
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/@common/Icons/ArrowDropDown.tsx
  frontend/src/components/@common/Icons/ArrowRight.tsx
  frontend/src/components/@common/Icons/Fragrance.tsx
  frontend/src/components/@common/Icons/Humidity.tsx
  frontend/src/components/@common/Icons/PottedPlant.tsx
  frontend/src/components/@common/Icons/Search.tsx
  frontend/src/components/@common/Icons/ThermometerSnow.tsx
  frontend/src/components/@common/Icons/ThermometerSun.tsx
  frontend/src/components/@common/Icons/Warning.tsx
  frontend/src/components/FormInput/index.tsx
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/Select/index.tsx
  frontend/src/pages/DictionaryDetail/index.tsx
  frontend/src/pages/Main/Main.style.tsx
  frontend/src/pages/Main/index.tsx
Labels: 🌈 기능, 🍇 프론트엔드

#107 build: frontend ci 작성
  .github/workflows/frontend-dev.yml
Labels: 🌎 인프라, 🍇 프론트엔드

#109 build: package-lock 파일 위치 지정
  .github/workflows/frontend-dev.yml
Labels: 🌎 인프라, 🍇 프론트엔드

#111 build: 프론트엔드 빌드 테스트 yml 수정
  .github/workflows/frontend-dev.yml
Labels: 🌎 인프라, 🍇 프론트엔드

#112 build: CI Result 구문 삭제
  .github/workflows/frontend-dev.yml
Labels: 🌈 기능, 🍇 프론트엔드

#115 build: continue-on-error 삭제
  .github/workflows/frontend-dev.yml
Labels: 🌎 인프라, 🍇 프론트엔드

#114 build: 히스토리 테이블 추가
  backend/pium/src/main/java/com/official/pium/domain/History.java
  backend/pium/src/main/resources/sql/schema.sql
Labels: 🌈 기능, 🍉 백엔드

#129 refactor: 반려 식물 등록 페이지
  frontend/src/apis/dictionary.ts
  frontend/src/apis/pet.ts
  frontend/src/components/FormInput/FormInput.stories.tsx
  frontend/src/components/FormInputBox/FormInputBox.stories.tsx
  frontend/src/components/FormInputBox/index.tsx
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/SearchResults/index.tsx
  frontend/src/components/Stack/Stack.stories.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/dictionary/useDictDetail.ts
  frontend/src/hooks/queries/dictionary/useDictSearch.ts
  frontend/src/hooks/useInvalidIdParams.ts
  frontend/src/pages/DictionaryDetail/index.tsx
  frontend/src/pages/Main/index.tsx
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/pages/PetRegister/Search/index.tsx
  frontend/src/router.tsx
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#134 refactor: 반려 식물 단건 조회
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/dto/PetPlantResponse.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
  backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
Labels: 🛠️ 리팩터링, 🍉 백엔드

#136 build: 트랙별 워크플로우 환경변수 구분
  .github/workflows/backend-dev.yml
  .github/workflows/frontend-dev.yml
Labels: 🌎 인프라, 🍇 프론트엔드, 🍉 백엔드

#146 refactor: 사용자 인증방식 추가
  backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
  backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
  backend/pium/src/main/java/com/official/pium/domain/Auth.java
  backend/pium/src/test/java/com/official/pium/RepositoryTest.java
  backend/pium/src/test/java/com/official/pium/UITest.java
  backend/pium/src/test/java/com/official/pium/repository/DictionaryPlantRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
Labels: 🛠️ 리팩터링, 🍉 백엔드, ♻️ 테스트

#153 fix: API 서버 https 적용에 따른 BASE_URL 수정
  frontend/src/constants/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storybookHandlers.ts
Labels: 🍇 프론트엔드, 🔔 긴급

#137 feat: 네비게이션 바 구현
  frontend/src/components/@common/Icons/Calendar.tsx
  frontend/src/components/@common/Icons/Home.tsx
  frontend/src/components/@common/Icons/Plant.tsx
  frontend/src/components/@common/Icons/Reminder.tsx
  frontend/src/components/@common/Navbar/Navbar.stories.tsx
  frontend/src/components/@common/Navbar/Navbar.style.ts
  frontend/src/components/@common/Navbar/index.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/DictionarySearch/DictionarySearch.style.ts
  frontend/src/pages/DictionarySearch/index.tsx
  frontend/src/pages/Main/Main.style.tsx
  frontend/src/pages/Main/index.tsx
  frontend/src/pages/PetRegister/Form/Form.style.ts
  frontend/src/pages/PetRegister/Search/Search.style.ts
  frontend/src/pages/PetRegister/Search/index.tsx
  frontend/src/pages/RootTemplate/RootTemplate.style.tsx
  frontend/src/pages/RootTemplate/index.tsx
  frontend/src/router.tsx
Labels: 🌈 기능, 🍇 프론트엔드

#150 feat: 내 반려 식물 상세 조회 페이지
  frontend/src/apis/pet.ts
  frontend/src/components/@common/Icons/Crown.tsx
  frontend/src/components/@common/Icons/Dictionary.tsx
  frontend/src/components/@common/Icons/Flowerpot.tsx
  frontend/src/components/@common/Icons/House.tsx
  frontend/src/components/@common/Icons/Sun.tsx
  frontend/src/components/@common/Icons/Wind.tsx
  frontend/src/components/@common/Image/Image.stories.tsx
  frontend/src/components/@common/Image/Image.style.ts
  frontend/src/components/@common/Image/index.tsx
  frontend/src/components/@common/Spinner/Spinner.stories.tsx
  frontend/src/components/@common/Spinner/Spinner.style.ts
  frontend/src/components/@common/Spinner/index.tsx
  frontend/src/components/PetDetails/PetDetails.stories.tsx
  frontend/src/components/PetDetails/PetDetails.style.ts
  frontend/src/components/PetDetails/index.tsx
  frontend/src/components/SearchBox/SearchBox.style.ts
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/SearchResultItem/index.tsx
  frontend/src/hooks/queries/pet/usePetPlantDetails.ts
  frontend/src/mocks/data/petPlants.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storage/PetPlant.ts
  frontend/src/mocks/storybookHandlers.ts
  frontend/src/pages/DictionaryDetail/DictionaryDetail.stories.tsx
  frontend/src/pages/DictionaryDetail/DictionaryDetail.style.ts
  frontend/src/pages/DictionaryDetail/index.tsx
  frontend/src/pages/PetDetails/index.tsx
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/router.tsx
  frontend/src/types/api/petPlant.ts
  frontend/src/utils/date.ts
Labels: 🌈 기능, 🍇 프론트엔드

#162 refactor: 테스트 support에서 사용하던 fixture 제거
  backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/MemberFixture.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 🛠️ 리팩터링, 🍉 백엔드, ♻️ 테스트
