Repository woowacourse-teams/2023-pium, pull requests merged in 2023-08, with the labels that each got.

#148 feat: 리마인더 기능 구현
  backend/pium/src/main/java/com/official/pium/controller/ReminderController.java
  backend/pium/src/main/java/com/official/pium/domain/DictionaryPlant.java
  backend/pium/src/main/java/com/official/pium/domain/History.java
  backend/pium/src/main/java/com/official/pium/domain/Member.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
  backend/pium/src/main/java/com/official/pium/service/ReminderService.java
  backend/pium/src/main/java/com/official/pium/service/dto/ReminderCreateRequest.java
  backend/pium/src/main/java/com/official/pium/service/dto/ReminderResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/ReminderUpdateRequest.java
  backend/pium/src/test/java/com/official/pium/controller/ReminderControllerTest.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
  backend/pium/src/test/java/com/official/pium/fixture/ReminderFixture.java
  backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 🌈 기능, 🍉 백엔드

#157 test: Cypress 자동화 테스트
  .github/workflows/frontend-e2e-test.yml
  frontend/cypress.config.ts
  frontend/cypress/e2e/dictDetails.cy.ts
  frontend/cypress/e2e/dictSearch.cy.ts
  frontend/cypress/e2e/main.cy.ts
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SearchBox/SearchBox.style.ts
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/SearchResults/SearchResults.style.ts
  frontend/src/components/SearchResults/index.tsx
  frontend/src/components/Select/index.tsx
  frontend/tsconfig.json
Labels: 🍇 프론트엔드, ♻️ 테스트

#147 feat: 토스트
  frontend/.storybook/decorators.tsx
  frontend/public/index.html
  frontend/src/components/@common/Icons/CheckCircle.tsx
  frontend/src/components/@common/Icons/CloseCircle.tsx
  frontend/src/components/@common/Icons/InfoCircle.tsx
  frontend/src/components/@common/Toast/Toast.stories.tsx
  frontend/src/components/@common/Toast/Toast.style.ts
  frontend/src/components/@common/Toast/ToastList.tsx
  frontend/src/components/@common/Toast/index.tsx
  frontend/src/constants/index.ts
  frontend/src/contexts/toastContext.tsx
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useToast.ts
  frontend/src/index.tsx
Labels: 🌈 기능, 🍇 프론트엔드

#142 feat: 리마인더 구현
  frontend/src/apis/reminder.ts
  frontend/src/components/@common/CheckBox/CheckBox.stories.ts
  frontend/src/components/@common/CheckBox/CheckBox.style.ts
  frontend/src/components/@common/CheckBox/index.tsx
  frontend/src/components/@common/Icons/CheckBoxEmpty.tsx
  frontend/src/components/@common/Icons/CheckBoxFill.tsx
  frontend/src/components/DateInput/DateInput.style.ts
  frontend/src/components/DateInput/index.tsx
  frontend/src/components/Reminder/Card/Card.stories.tsx
  frontend/src/components/Reminder/Card/Card.style.ts
  frontend/src/components/Reminder/Card/index.tsx
  frontend/src/components/Reminder/CardBox/CardBox.stories.tsx
  frontend/src/components/Reminder/CardBox/CardBox.style.ts
  frontend/src/components/Reminder/CardBox/index.tsx
  frontend/src/components/Reminder/MonthBox/MonthBox.stories.tsx
  frontend/src/components/Reminder/MonthBox/MonthBox.style.ts
  frontend/src/components/Reminder/MonthBox/index.tsx
  frontend/src/contexts/reminderContext.tsx
  frontend/src/hooks/queries/reminder/useChangeDate.ts
  frontend/src/hooks/queries/reminder/useReminder.ts
  frontend/src/hooks/queries/reminder/useWater.ts
  frontend/src/hooks/useReminderHooks.ts
  frontend/src/mocks/data/reminder.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storage/Reminder.ts
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/pages/Reminder/Reminder.style.ts
  frontend/src/pages/Reminder/index.tsx
  frontend/src/router.tsx
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
  frontend/src/types/api/DataResponse.ts
  frontend/src/types/api/reminder.ts
  frontend/src/utils/date.ts
Labels: 🌈 기능, 🍇 프론트엔드

#156 feat: 반려 식물 목록 페이지 구현
  frontend/src/apis/pet.ts
  frontend/src/components/PetCard/PetCard.stories.tsx
  frontend/src/components/PetCard/PetCard.style.ts
  frontend/src/components/PetCard/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/pet/usePetPlantCardList.ts
  frontend/src/mocks/data/petPlantCardList.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/PetList/PetList.style.ts
  frontend/src/pages/PetList/index.tsx
  frontend/src/router.tsx
  frontend/src/types/api/petPlant.ts
Labels: 🌈 기능, 🍇 프론트엔드

#175 refactor: 리마인더 조회 정렬 추가
  backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
  backend/pium/src/main/java/com/official/pium/service/ReminderService.java
  backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
Labels: 🛠️ 리팩터링, 🍉 백엔드

#172 feat: 반려 식물 조회 사용자 검증 기능 추가
  backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
  backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
  backend/pium/src/main/java/com/official/pium/controller/ReminderController.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/ReminderService.java
  backend/pium/src/main/java/com/official/pium/service/dto/PetPlantResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/ReminderResponse.java
  backend/pium/src/test/java/com/official/pium/UITest.java
  backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/ReminderControllerTest.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
  backend/pium/src/test/java/com/official/pium/fixture/MemberFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/ReminderFixture.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
Labels: 🌈 기능, 🛠️ 리팩터링, 🍉 백엔드, ♻️ 테스트

#149 feat: 단건 히스토리 조회 페이징 기능 구현
  backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/mapper/HistoryMapper.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
  backend/pium/src/main/java/com/official/pium/service/HistoryService.java
  backend/pium/src/main/java/com/official/pium/service/dto/HistoryResponse.java
  backend/pium/src/test/java/com/official/pium/IntegrationTest.java
  backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
  backend/pium/src/test/java/com/official/pium/fixture/HistoryFixture.java
  backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/HistorySupport.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 🌈 기능, 🍉 백엔드

#182 refactor: 핵심 기능 스크린 리더를 활용한 웹 접근성 수정
  frontend/.storybook/main.ts
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/@common/Calendar/Calendar.stories.tsx
  frontend/src/components/@common/Calendar/Calendar.style.ts
  frontend/src/components/@common/Calendar/DaySmallBox/DaySmallBox.stories.tsx
  frontend/src/components/@common/Calendar/DaySmallBox/DaySmallBox.style.ts
  frontend/src/components/@common/Calendar/DaySmallBox/index.tsx
  frontend/src/components/@common/Calendar/index.tsx
  frontend/src/components/@common/Icons/ArrowLeft.tsx
  frontend/src/components/@common/Icons/ArrowRight.tsx
  frontend/src/components/@common/Icons/ArrowRightAlt.tsx
  frontend/src/components/@common/Modal/Modal.style.ts
  frontend/src/components/@common/Modal/index.tsx
  frontend/src/components/@common/Navbar/Navbar.style.ts
  frontend/src/components/@common/Toast/Toast.style.ts
  frontend/src/components/DateInput/DateInput.stories.tsx
  frontend/src/components/DateInput/DateInput.style.ts
  frontend/src/components/DateInput/index.tsx
  frontend/src/components/FormInput/index.tsx
  frontend/src/components/FormInputBox/FormInputBox.stories.tsx
  frontend/src/components/PetCard/index.tsx
  frontend/src/components/PetPlantEditForm/index.tsx
  frontend/src/components/Reminder/Card/Card.stories.tsx
  frontend/src/components/Reminder/Card/Card.style.ts
  frontend/src/components/Reminder/Card/index.tsx
  frontend/src/components/Reminder/CardBox/CardBox.stories.tsx
  frontend/src/components/Reminder/CardBox/CardBox.style.ts
  frontend/src/components/Reminder/CardBox/index.tsx
  frontend/src/components/Reminder/MonthBox/MonthBox.stories.tsx
  frontend/src/components/Reminder/MonthBox/MonthBox.style.ts
  frontend/src/components/Reminder/MonthBox/index.tsx
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/Select/Select.style.ts
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/reminder/useReminder.ts
  frontend/src/hooks/useCalendar.ts
  frontend/src/hooks/useDateInput.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useReminderHooks.ts
  frontend/src/mocks/data/petPlants.ts
  frontend/src/mocks/data/reminder.ts
  frontend/src/mocks/storage/Reminder.ts
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/pages/Reminder/Reminder.style.ts
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
  frontend/src/types/api/reminder.ts
  frontend/src/types/date.ts
  frontend/src/utils/date.ts
  frontend/src/utils/validate.ts
Labels: 🌈 기능, 🛠️ 리팩터링, 🍇 프론트엔드

#189 fix: 히스토리 api 변경
  frontend/src/apis/history.ts
  frontend/src/mocks/handlers.ts
Labels: 🐛 버그, 🍇 프론트엔드, 🔔 긴급

#190 fix: date 입력 형태 'YYYY-MM-DD' 형태에서 YYYY,MM,DD 형태로 변경
  frontend/src/hooks/useCalendar.ts
  frontend/src/utils/date.ts
Labels: 🐛 버그, 🛠️ 리팩터링, 🍇 프론트엔드, 🔔 긴급

#192 fix: 생일을 월 일 기준으로 계산
  frontend/src/components/PetPlantCard/index.tsx
Labels: 🍇 프론트엔드

#223 chore/github actions build test 조건 변경
  .github/workflows/frontend-dev.yml
Labels: 🍇 프론트엔드, ♻️ 테스트

#234 refactor: 스키마 최신화 및 테스트 코드 수정
  backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
  backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
  backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
  backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
  backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
  backend/pium/src/main/java/com/official/pium/domain/Auth.java
  backend/pium/src/main/java/com/official/pium/domain/BaseEntity.java
  backend/pium/src/main/java/com/official/pium/domain/History.java
  backend/pium/src/main/java/com/official/pium/domain/HistoryCategory.java
  backend/pium/src/main/java/com/official/pium/domain/HistoryContent.java
  backend/pium/src/main/java/com/official/pium/domain/HistoryType.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/exception/dto/GlobalExceptionResponse.java
  backend/pium/src/main/java/com/official/pium/mapper/HistoryMapper.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/repository/DictionaryPlantRepository.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryCategoryRepository.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
  backend/pium/src/main/java/com/official/pium/service/DictionaryPlantService.java
  backend/pium/src/main/java/com/official/pium/service/HistoryService.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/ReminderService.java
  backend/pium/src/main/java/com/official/pium/service/dto/DataResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/DictionaryPlantSearchResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/HistoryResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/PetPlantCreateRequest.java
  backend/pium/src/main/java/com/official/pium/service/dto/PetPlantResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/SingleHistoryResponse.java
  backend/pium/src/main/java/com/official/pium/service/dto/SinglePetPlantResponse.java
  backend/pium/src/main/resources/sql/schema.sql
  backend/pium/src/test/java/com/official/pium/AcceptanceTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/DictionaryPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/ReminderApiTest.java
  backend/pium/src/test/java/com/official/pium/config/DatabaseCleaner.java
  backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
  backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/HistoryFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
  backend/pium/src/test/java/com/official/pium/repository/DictionaryPlantRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/HistoryCategorySupport.java
  backend/pium/src/test/java/com/official/pium/support/HistorySupport.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 🛠️ 리팩터링, 🍉 백엔드

#231 feat: 반려 식물 삭제 기능 구현
  backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/resources/sql/schema.sql
  backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/config/DatabaseCleaner.java
  backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
  backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
Labels: 🌈 기능, 🍉 백엔드

#229 refactor: 내비게이션 바 리팩터링과 cypress 테스트
  frontend/cypress/e2e/navbar.cy.ts
  frontend/src/components/@common/Navbar/Navbar.stories.tsx
  frontend/src/components/@common/Navbar/Navbar.style.ts
  frontend/src/components/@common/Navbar/index.tsx
  frontend/src/components/petPlant/PetPlantDetail/PetPlantDetail.style.ts
  frontend/src/pages/DictionaryDetail/DictionaryDetail.style.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드, ♻️ 테스트

#240 refactor: 달력, 모달, 그리고 DateFormat
  frontend/src/components/@common/Calendar/Calendar.style.ts
  frontend/src/components/@common/Calendar/DaySmallBox/DaySmallBox.style.ts
  frontend/src/components/@common/Calendar/DaySmallBox/index.tsx
  frontend/src/components/@common/Calendar/index.tsx
  frontend/src/components/@common/DateInput/DateInput.stories.tsx
  frontend/src/components/@common/DateInput/index.tsx
  frontend/src/components/petPlant/PetPlantCard/PetPlantCard.stories.tsx
  frontend/src/components/petPlant/PetPlantEditForm/index.tsx
  frontend/src/components/reminder/Card/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useDateInput.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useNumberInput.ts
  frontend/src/hooks/usePetPlantForm.ts
  frontend/src/mocks/storage/PetPlant.ts
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/types/date.ts
  frontend/src/types/history.ts
  frontend/src/types/petPlant.ts
  frontend/src/types/reminder.ts
  frontend/src/utils/date.ts
  frontend/src/utils/validate.ts
Labels: 🌈 기능, 🛠️ 리팩터링, 🍇 프론트엔드

#237 test: RestDocs 적용
  backend/pium/.gitignore
  backend/pium/build.gradle
  backend/pium/src/docs/asciidoc/dictionaryPlant.adoc
  backend/pium/src/docs/asciidoc/history.adoc
  backend/pium/src/docs/asciidoc/index.adoc
  backend/pium/src/docs/asciidoc/petPlant.adoc
  backend/pium/src/docs/asciidoc/reminder.adoc
  backend/pium/src/test/java/com/official/pium/UITest.java
  backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/ReminderApiTest.java
  backend/pium/src/test/java/com/official/pium/config/DatabaseCleaner.java
  backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/controller/ReminderControllerTest.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
  backend/pium/src/test/java/com/official/pium/fixture/DictionaryPlantFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
  backend/pium/src/test/java/com/official/pium/fixture/ReminderFixture.java
  backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 📝 문서, 🍉 백엔드, ♻️ 테스트

#246 feat: 반려 식물 물 주기 수정동작 보완
  backend/pium/src/main/java/com/official/pium/domain/HistoryCategory.java
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/test/java/com/official/pium/IntegrationTest.java
  backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/config/DatabaseClearExtension.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
  backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
  backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
  backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
  backend/pium/src/test/java/com/official/pium/support/HistoryCategorySupport.java
  backend/pium/src/test/java/com/official/pium/support/HistorySupport.java
  backend/pium/src/test/java/com/official/pium/support/PetPlantSupport.java
Labels: 🌈 기능, 🍉 백엔드

#250 refactor: eslint react hooks recommended 설정 및 리팩터링
  frontend/.eslintrc
  frontend/src/components/@common/Calendar/DaySmallBox/DaySmallBox.style.ts
  frontend/src/components/@common/DateInput/DateInput.stories.tsx
  frontend/src/components/@common/FormInput/FormInput.stories.tsx
  frontend/src/components/@common/FormInput/index.tsx
  frontend/src/components/@common/Select/Select.stories.tsx
  frontend/src/components/@common/Stack/Stack.stories.tsx
  frontend/src/components/@common/Toast/Toast.stories.tsx
  frontend/src/components/@common/Toast/index.tsx
  frontend/src/hooks/useDictrionaryNavigate.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/usePetPlantForm.ts
  frontend/src/pages/PetPlantTimeline/index.tsx
  frontend/src/pages/PetRegister/Form/index.tsx
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#252 refactor: 히스토리 이벤트 방식으로 수정
  backend/pium/src/main/java/com/official/pium/event/history/HistoryEvent.java
  backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
  backend/pium/src/main/java/com/official/pium/event/history/PetPlantHistory.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/service/ReminderService.java
  backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
Labels: 🛠️ 리팩터링, 🍉 백엔드

#254 refactor: 토스트에 리코일을 적용하여 최적화
  frontend/.storybook/decorators.tsx
  frontend/src/App.tsx
  frontend/src/components/@common/Calendar/Calendar.stories.tsx
  frontend/src/components/@common/DateInput/DateInput.stories.tsx
  frontend/src/components/@common/Toast/Toast.stories.tsx
  frontend/src/components/@common/Toast/Toast.style.ts
  frontend/src/components/@common/Toast/ToastList.tsx
  frontend/src/components/@common/Toast/index.tsx
  frontend/src/components/petPlant/PetPlantEditForm/PetPlantEditForm.stories.tsx
  frontend/src/components/petPlant/PetPlantEditForm/index.tsx
  frontend/src/components/reminder/Card/Card.stories.tsx
  frontend/src/components/reminder/Card/index.tsx
  frontend/src/components/reminder/CardBox/CardBox.stories.tsx
  frontend/src/components/reminder/MonthBox/MonthBox.stories.tsx
  frontend/src/constants/index.ts
  frontend/src/contexts/toastContext.tsx
  frontend/src/hooks/queries/pet/useEditPetPlant.ts
  frontend/src/hooks/queries/pet/useRegisterPetPlant.ts
  frontend/src/hooks/useAddToast.ts
  frontend/src/hooks/useDateInput.ts
  frontend/src/hooks/useReminderHooks.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/PetPlantEdit/index.tsx
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/store/atoms/toasts.ts
  frontend/src/types/toast.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#256 feat: 반려식물 등록 시 히스토리 추가
  backend/pium/src/main/java/com/official/pium/event/history/PetPlantHistory.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
  backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
Labels: 🌈 기능, 🍉 백엔드

#260 refacrtor: 반려 식물 수정 페이지 리팩터링, Select 접근성 개선
  frontend/cypress/e2e/petPlantEdit.cy.ts
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/src/components/@common/Calendar/DaySmallBox/DaySmallBox.style.ts
  frontend/src/components/@common/Calendar/DaySmallBox/index.tsx
  frontend/src/components/@common/Calendar/index.tsx
  frontend/src/components/@common/DateInput/index.tsx
  frontend/src/components/@common/Select/Select.style.ts
  frontend/src/components/@common/Select/index.tsx
  frontend/src/components/petPlant/PetPlantDetail/PetPlantDetail.style.ts
  frontend/src/components/petPlant/PetPlantEditForm/PetPlantEditForm.style.ts
  frontend/src/components/petPlant/PetPlantEditForm/index.tsx
  frontend/src/mocks/data/petPlants.ts
  frontend/src/mocks/storage/PetPlant.ts
  frontend/src/types/petPlant.ts
  frontend/src/utils/date.ts
Labels: 🐛 버그, 🛠️ 리팩터링, 🍇 프론트엔드

#269 fix: 반려 식물 정보 업데이트 시 lastWaterDate 검증조건 추가
  backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
  backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
Labels: 🐛 버그, 🍉 백엔드

#258 feat: 타임라인 페이지 고도화
  frontend/src/apis/history.ts
  frontend/src/components/@common/CheckButton/CheckButton.stories.ts
  frontend/src/components/@common/CheckButton/CheckButton.style.ts
  frontend/src/components/@common/CheckButton/index.tsx
  frontend/src/components/@common/DateInput/index.tsx
  frontend/src/components/@common/Icons/Stopwatch.tsx
  frontend/src/components/@common/Icons/TreePlantPot.tsx
  frontend/src/components/@common/Icons/Water.tsx
  frontend/src/components/@common/Navbar/Navbar.style.ts
  frontend/src/components/@common/Toast/Toast.stories.tsx
  frontend/src/components/petPlant/Timeline/Timeline.style.ts
  frontend/src/components/petPlant/Timeline/converter.ts
  frontend/src/components/petPlant/Timeline/index.tsx
  frontend/src/components/petPlant/TimelineItemList/TimelineItemList.style.ts
  frontend/src/components/petPlant/TimelineItemList/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/history/useYearList.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useToggle.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/history.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/handlers/historyHandlers.ts
  frontend/src/pages/PetPlantTimeline/PetPlantTimeline.style.ts
  frontend/src/pages/PetPlantTimeline/converter.ts
  frontend/src/pages/PetPlantTimeline/index.tsx
  frontend/src/router.tsx
  frontend/src/style/styles.d.ts
  frontend/src/style/theme.style.ts
  frontend/src/types/history.ts
  frontend/src/utils/createObserver.ts
Labels: 🌈 기능, 🛠️ 리팩터링, 🍇 프론트엔드

#263 feat: 반려 식물 삭제, confirm 기능
  frontend/src/App.tsx
  frontend/src/apis/pet.ts
  frontend/src/components/@common/Confirm/Confirm.stories.tsx
  frontend/src/components/@common/Confirm/Confirm.style.ts
  frontend/src/components/@common/Confirm/index.tsx
  frontend/src/components/@common/Modal/Modal.style.ts
  frontend/src/components/petPlant/PetPlantDetail/PetPlantDetail.style.ts
  frontend/src/components/petPlant/PetPlantDetail/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/pet/useDeletePetPlant.ts
  frontend/src/hooks/useConfirm.ts
  frontend/src/hooks/useConfirmModal.ts
  frontend/src/hooks/useModal.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/storage/PetPlant.ts
  frontend/src/store/atoms/confirm.ts
Labels: 🌈 기능, 🍇 프론트엔드

#270 refactor: 사전 식물 정보, 반려 식물 카드 목록 overflow-x, favicon
  frontend/cypress/e2e/dictDetails.cy.ts
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/android-icon-144x144.png
  frontend/public/assets/android-icon-192x192.png
  frontend/public/assets/android-icon-36x36.png
  frontend/public/assets/android-icon-48x48.png
  frontend/public/assets/android-icon-72x72.png
  frontend/public/assets/android-icon-96x96.png
  frontend/public/assets/apple-icon-114x114.png
  frontend/public/assets/apple-icon-120x120.png
  frontend/public/assets/apple-icon-144x144.png
  frontend/public/assets/apple-icon-152x152.png
  frontend/public/assets/apple-icon-180x180.png
  frontend/public/assets/apple-icon-57x57.png
  frontend/public/assets/apple-icon-60x60.png
  frontend/public/assets/apple-icon-72x72.png
  frontend/public/assets/apple-icon-76x76.png
  frontend/public/assets/apple-icon-precomposed.png
  frontend/public/assets/apple-icon.png
  frontend/public/assets/browserconfig.xml
  frontend/public/assets/favicon-16x16.png
  frontend/public/assets/favicon-32x32.png
  frontend/public/assets/favicon-96x96.png
  frontend/public/assets/favicon.ico
  frontend/public/assets/manifest.json
  frontend/public/assets/ms-icon-144x144.png
  frontend/public/assets/ms-icon-150x150.png
  frontend/public/assets/ms-icon-310x310.png
  frontend/public/assets/ms-icon-70x70.png
  frontend/public/index.html
  frontend/src/components/@common/Icons/ManageLevel.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/data/dictionaryPlant.ts
  frontend/src/mocks/data/petPlantCardList.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/DictionaryDetail/index.tsx
  frontend/src/pages/PetPlantCardList/PetPlantCardList.style.ts
  frontend/src/types/dictionaryPlant.ts
  frontend/webpack.config.js
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#261 feat: Logback을 이용한 서버 로깅 설정
  backend/pium/build.gradle
  backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
  backend/pium/src/main/resources/console-appender.xml
  backend/pium/src/main/resources/file-error-appender.xml
  backend/pium/src/main/resources/file-info-appender.xml
  backend/pium/src/main/resources/logback-spring.xml
  backend/pium/src/main/resources/slack-notification-appender.xml
Labels: 🌈 기능, 🌎 인프라, 🍉 백엔드

#273 feat: 반려식물 단건 히스토리 조회에서 필터링 추가
  backend/pium/.gitignore
  backend/pium/build.gradle
  backend/pium/src/main/java/com/official/pium/config/QueryDslConfig.java
  backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepository.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepositoryImpl.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
  backend/pium/src/main/java/com/official/pium/service/HistoryService.java
  backend/pium/src/test/java/com/official/pium/RepositoryTest.java
  backend/pium/src/test/java/com/official/pium/UITest.java
  backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
  backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
  backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
  backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
Labels: 🌈 기능, 🍉 백엔드

#283 docs: README 작성
  README.md
Labels: 📝 문서, 🍇 프론트엔드, 🍉 백엔드

#272 feat: 로그인 기능을 구현한다.
  frontend/.prettierrc
  frontend/cypress/e2e/navbar.cy.ts
  frontend/cypress/e2e/petPlantEdit.cy.ts
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/src/App.tsx
  frontend/src/apis/auth.ts
  frontend/src/apis/history.ts
  frontend/src/apis/pet.ts
  frontend/src/apis/reminder.ts
  frontend/src/components/@common/ErrorBoundary/index.ts
  frontend/src/components/@common/Icons/AccountCircle.tsx
  frontend/src/components/@common/Icons/KakaoLoginLarge.tsx
  frontend/src/components/@common/Navbar/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/queries/auth/useCheckSessionId.ts
  frontend/src/hooks/queries/auth/useLogin.ts
  frontend/src/hooks/queries/auth/useLogout.ts
  frontend/src/hooks/queries/auth/useWithdraw.ts
  frontend/src/hooks/queries/history/useYearList.ts
  frontend/src/hooks/queries/pet/useEditPetPlant.ts
  frontend/src/hooks/queries/pet/usePetPlantCardList.ts
  frontend/src/hooks/queries/pet/usePetPlantDetails.ts
  frontend/src/hooks/queries/pet/useRegisterPetPlant.ts
  frontend/src/hooks/queries/reminder/useChangeDate.ts
  frontend/src/hooks/queries/reminder/useReminder.ts
  frontend/src/hooks/queries/reminder/useWater.ts
  frontend/src/hooks/useUnauthorize.ts
  frontend/src/mocks/handlers.ts
  frontend/src/models/statusError.ts
  frontend/src/pages/Error/Error.style.ts
  frontend/src/pages/Error/NotFound.tsx
  frontend/src/pages/Error/Unauthorize.tsx
  frontend/src/pages/Login/Authorization.tsx
  frontend/src/pages/Login/Login.style.ts
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/MyPage/MyPage.style.ts
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/RootTemplate/index.tsx
  frontend/src/router.tsx
  frontend/src/types/DataResponse.ts
  frontend/src/utils/throwOnInvalidStatus.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 🌈 기능, 🍇 프론트엔드

#290 hotfix: `crdential` 추가 및 history filter에 "" 제거
  frontend/src/apis/auth.ts
  frontend/src/apis/history.ts
  frontend/src/apis/pet.ts
Labels: 🐛 버그, 🛠️ 리팩터링, 🍇 프론트엔드, 🔔 긴급

#296 refactor: getSessionId에 credentials 추가
  frontend/src/apis/auth.ts
Labels: 🐛 버그, 🍇 프론트엔드

#298 refactor: 백엔드 코드 리팩터링
  README.md
  backend/pium/src/docs/asciidoc/history.adoc
  backend/pium/src/docs/asciidoc/petPlant.adoc
  backend/pium/src/docs/asciidoc/reminder.adoc
  backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
  backend/pium/src/main/java/com/official/pium/domain/History.java
  backend/pium/src/main/java/com/official/pium/event/history/HistoryEvent.java
  backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
  backend/pium/src/main/java/com/official/pium/event/history/PetPlantHistory.java
  backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepository.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryCustomRepositoryImpl.java
  backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantCustomRepository.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantCustomRepositoryImpl.java
  backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
  backend/pium/src/main/java/com/official/pium/service/HistoryService.java
  backend/pium/src/main/java/com/official/pium/service/MemberService.java
  backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
  backend/pium/src/main/java/com/official/pium/service/ReminderService.java
  backend/pium/src/main/java/com/official/pium/service/dto/PetPlantResponse.java
  backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
  backend/pium/src/test/java/com/official/pium/domain/HistoryTest.java
  backend/pium/src/test/java/com/official/pium/service/MemberServiceTest.java
Labels: 🌈 기능, 🛠️ 리팩터링, 🍉 백엔드

#300 feat: 운영 서버 로그 알림 추가
  backend/pium/src/main/resources/logback-spring.xml
  backend/pium/src/main/resources/slack-notification-dev-appender.xml
Labels: 🌎 인프라, 🍉 백엔드

#302 fix: 운영 서버 로그 알림 추가
  backend/pium/src/main/resources/slack-notification-prod-appender.xml
Labels: 🌎 인프라, 🍉 백엔드

#304 build: flyway 도입
  backend/pium/build.gradle
  backend/pium/src/main/resources/application.properties
  backend/pium/src/main/resources/db/migration/V1__init.sql
  backend/pium/src/main/resources/db/migration/V2__remove_email.sql
  backend/pium/src/test/resources/application.properties
Labels: 🌎 인프라, 🍉 백엔드

#284 feat: 에러바운더리 초기화 기능
  frontend/cypress/e2e/auth.cy.ts
  frontend/cypress/e2e/navbar.cy.ts
  frontend/cypress/e2e/petPlantEdit.cy.ts
  frontend/cypress/e2e/petRegister.cy.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/utils/login.ts
  frontend/src/App.tsx
  frontend/src/components/@common/ErrorBoundary/index.ts
  frontend/src/components/@common/ErrorBoundary/index.tsx
  frontend/src/components/@common/Navbar/index.tsx
  frontend/src/components/@common/Redirect/index.tsx
  frontend/src/components/petPlant/PetPlantDetail/PetPlantDetail.style.ts
  frontend/src/constants/index.ts
  frontend/src/contexts/resetErrorBoundaryContext.tsx
  frontend/src/hooks/queries/auth/useCheckSessionId.ts
  frontend/src/hooks/queries/auth/useLogin.ts
  frontend/src/hooks/queries/auth/useLogout.ts
  frontend/src/hooks/queries/auth/useWithdraw.ts
  frontend/src/hooks/queries/history/useYearList.ts
  frontend/src/hooks/queries/pet/useEditPetPlant.ts
  frontend/src/hooks/queries/pet/usePetPlantCardList.ts
  frontend/src/hooks/queries/pet/usePetPlantDetails.ts
  frontend/src/hooks/queries/pet/useRegisterPetPlant.ts
  frontend/src/hooks/queries/reminder/useChangeDate.ts
  frontend/src/hooks/queries/reminder/useReminder.ts
  frontend/src/hooks/queries/reminder/useWater.ts
  frontend/src/hooks/useResetErrorBoundary.ts
  frontend/src/hooks/useUnauthorize.ts
  frontend/src/pages/Error/NotFound.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/PetPlantTimeline/index.tsx
  frontend/src/pages/PetRegister/Form/index.tsx
  frontend/src/pages/PetRegister/Search/index.tsx
  frontend/src/pages/RootTemplate/index.tsx
  frontend/src/utils/noRetryIfUnauthorized.ts
  frontend/src/utils/throwOnInvalidStatus.ts
Labels: 🌈 기능, 🍇 프론트엔드

#306 feat: 로그인 페이지에 이미지 추가
  frontend/src/components/@common/Icons/AccountCircle.tsx
  frontend/src/components/@common/Navbar/index.tsx
  frontend/src/pages/Login/Login.style.ts
  frontend/src/pages/Login/index.tsx
Labels: 🍇 프론트엔드
