Repository woowacourse-teams/2023-pium, pull requests merged in 2024-01, with the labels that each got.

#487 test: 알림 기능 테스트 메서드 추가
  backend/pium/src/main/java/com/official/pium/admin/ui/AdminPageController.java
  backend/pium/src/main/java/com/official/pium/petPlant/application/ReminderService.java
  backend/pium/src/test/java/com/official/pium/admin/controller/AdminPageControllerTest.java
Labels: 🍉 백엔드, ♻️ 테스트

#489 fix: 이벤트 리스터 인자 타입 수정
  backend/pium/src/main/java/com/official/pium/notification/application/NotificationEventListener.java
  backend/pium/src/main/java/com/official/pium/petPlant/application/ReminderService.java
  backend/pium/src/main/java/com/official/pium/petPlant/event/notification/NotificationEvents.java
Labels: 🐛 버그, 🍉 백엔드

#491 refactor: toggle UI/UX
  frontend/public/devLocalServiceWorker.js
  frontend/public/firebase-messaging-sw.js
  frontend/public/index.html
  frontend/src/assets/firefox_add_button.png
  frontend/src/components/@common/InstallPrompt/InstallPrompt.style.ts
  frontend/src/components/@common/InstallPrompt/index.tsx
  frontend/src/components/@common/Spinner/Spinner.style.ts
  frontend/src/components/@common/Spinner/index.tsx
  frontend/src/components/mypage/PushAlert/index.tsx
  frontend/src/hooks/@common/useInstallApp.ts
  frontend/src/hooks/@common/usePushAlert.ts
  frontend/src/hooks/firebase/useGetToken.ts
  frontend/src/hooks/queries/auth/useWebPush.ts
  frontend/src/models/FCMMessaging.ts
  frontend/src/models/statusError.ts
  frontend/src/pages/@common/Home/index.tsx
  frontend/src/pages/reminder/ReminderPage/index.tsx
  frontend/src/registerServiceWork.ts
  frontend/src/types/global.d.ts
  frontend/src/utils/cookie.ts
  frontend/src/utils/throwOnInvalidStatus.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#495 refactor: 토글 UI 제거 및 낙관적 업데이트 적용
  frontend/src/hooks/firebase/useGetToken.ts
  frontend/src/hooks/queries/auth/useWebPush.ts
  frontend/src/models/PushStatus.ts
  frontend/src/registerServiceWork.ts
Labels: 🛠️ 리팩터링, 🍇 프론트엔드

#497 refactor: 알림 기능 로직 개선 및 알림 테스트 추가
  backend/pium/src/main/java/com/official/pium/admin/service/TestService.java
  backend/pium/src/main/java/com/official/pium/admin/ui/AdminPageController.java
  backend/pium/src/main/java/com/official/pium/admin/ui/TestController.java
  backend/pium/src/main/java/com/official/pium/config/AsyncConfig.java
  backend/pium/src/main/java/com/official/pium/member/application/MemberService.java
  backend/pium/src/main/java/com/official/pium/member/ui/MemberController.java
  backend/pium/src/main/java/com/official/pium/notification/application/NotificationEventListener.java
  backend/pium/src/main/java/com/official/pium/notification/application/NotificationService.java
  backend/pium/src/main/java/com/official/pium/petPlant/application/ReminderService.java
  backend/pium/src/main/java/com/official/pium/petPlant/event/notification/NotificationEvents.java
  backend/pium/src/test/java/com/official/pium/admin/controller/AdminPageControllerTest.java
  backend/pium/src/test/java/com/official/pium/member/application/MemberServiceTest.java
  backend/pium/src/test/java/com/official/pium/notification/application/NotificationEventListenerTest.java
  backend/pium/src/test/java/com/official/pium/notification/application/NotificationServiceTest.java
Labels: 🛠️ 리팩터링, 🍉 백엔드

#499 refactor: fcm 서버 비동기 처리 구현
  backend/pium/src/main/java/com/official/pium/admin/service/TestService.java
  backend/pium/src/main/java/com/official/pium/admin/ui/TestController.java
  backend/pium/src/main/java/com/official/pium/notification/fcm/application/FcmMessageSender.java
  backend/pium/src/main/resources/application.yml
  backend/pium/src/test/resources/application.yml
Labels: 🛠️ 리팩터링, 🍉 백엔드
